### ISSUE TITLE
I am unable to fix the issue with the code created by Martin Mauch nightscape.. I am also trying to create a scala code for  landing excel data from sharepoint to hadoop and then convert it into parquet format.I am getting error saying value InferSchema not found

### ISSUE THREAD

**Issue by bssulfikkar** [crealytics/spark-excel#1]
import java.math.BigDecimal
4	import java.sql.{Date, Timestamp}
5	import java.text.NumberFormat
6	import java.util.Locale
7	import java.io._
8	import scala.collection.JavaConverters._
9	import org.apache.poi.ss.usermodel.{ WorkbookFactory, Row => SheetRow, Cell, DataFormatter }
10	import org.apache.spark.rdd.RDD
11	import org.apache.spark.sql._
12	import org.apache.spark.sql.sources._
13	import org.apache.spark.sql.types._
14	
15	import scala.util.Try
16	
17	case class ExcelRelation(
18	  location: String,
19	  sheetName: String,
20	  useHeader: Boolean,
21	  treatEmptyValuesAsNulls: Boolean,
22	  inferSheetSchema: Boolean,
23	  addColorColumns: Boolean = true,
24	  userSchema: StructType = null
25	  )
26	  (@transient val sqlContext: SQLContext)
27	extends BaseRelation with TableScan with PrunedScan {
28	  val workbook = WorkbookFactory.create(new FileInputStream(location))
29	  val sheet = workbook.getSheet(sheetName)
30	  val headers = sheet.getRow(0).cellIterator().asScala.to[Vector]
31	  override val schema: StructType = inferSchema
32	  val dataFormatter = new DataFormatter();
33	  override def buildScan: RDD[Row] = buildScan(schema.map(_.name).toArray)
34	
35	  override def buildScan(requiredColumns: Array[String]): RDD[Row] = {
36	    val lookups = requiredColumns.map {c =>
37	      val columnNameRegex = s"(.*?)(_color)?".r
38	      val columnNameRegex(columnName, isColor) = c
39	      val columnIndex = schema.indexWhere(_.name == columnName)
40	
41	      val cellExtractor: Cell => Any = if (isColor == null) {
42	        { cell: Cell =>
43	          val value = cell.getCellType match {
44	            case Cell.CELL_TYPE_NUMERIC => cell.getNumericCellValue
45	            case Cell.CELL_TYPE_BOOLEAN => cell.getBooleanCellValue
46	            case Cell.CELL_TYPE_STRING => cell.getStringCellValue
47	            case t => throw new RuntimeException(s"Unknown cell type $t for $cell")
48	          }
49	          castTo(value.toString, schema(columnIndex).dataType)
50	        }
51	      } else {
52	        _.getCellStyle.getFillForegroundColorColor match {
53	          case null => ""
54	          case c: org.apache.poi.xssf.usermodel.XSSFColor => c.getARGBHex
55	          case c => throw new RuntimeException(s"Unknown color type $c: ${c.getClass}")
56	        }
57	      }
58	      { row: SheetRow =>
59	        val cell = row.getCell(columnIndex)
60	        if (cell == null) {
61	          null
62	        } else {
63	          cellExtractor(cell)
64	        }
65	      }
66	    }.to[Vector]
67	    val rows = sheet.rowIterator().asScala.drop(1).map(row => lookups.map(l => l(row)))
68	    val result = rows.to[Vector]
69	
70	    sqlContext.sparkContext.parallelize(result.map(Row.fromSeq))
71	  }
72	
73	  // Cast a String to a Spark Data Type
74	  private def castTo(datum: String, castType: DataType): Any = {
75	    castType match {
76	      case _: ByteType => datum.toByte
77	      case _: ShortType => datum.toShort
78	      case _: IntegerType => datum.toInt
79	      case _: LongType => datum.toLong
80	      case _: FloatType => Try(datum.toFloat)
81	        .getOrElse(NumberFormat.getInstance(Locale.getDefault).parse(datum).floatValue())
82	      case _: DoubleType => Try(datum.toDouble)
83	        .getOrElse(NumberFormat.getInstance(Locale.getDefault).parse(datum).doubleValue())
84	      case _: BooleanType => datum.toBoolean
85	      case _: DecimalType => new BigDecimal(datum.replaceAll(",", ""))
86	      case _: TimestampType => Timestamp.valueOf(datum)
87	      case _: DateType => Date.valueOf(datum)
88	      case _: StringType => datum
89	      case _ => throw new RuntimeException(s"Unsupported type: ${castType.typeName}")
90	    }
91	  }
92	
93	  private def rowsRdd: RDD[SheetRow] = {
94	    parallelize(sheet.rowIterator().asScala.toSeq)
95	  }
96	  private def parallelize[T: scala.reflect.ClassTag](seq: Seq[T]): RDD[T] = sqlContext.sparkContext.parallelize(seq)
97	  private def inferSchema(): StructType = {
98	    if (this.userSchema != null) {
99	      userSchema
100	    } else {
101	      val firstRow = headers
102	      val header = if (useHeader) {
103	        firstRow.map(_.getStringCellValue)
104	      } else {
105	        firstRow.zipWithIndex.map { case (value, index) => s"C$index"}
106	      }
107	      val baseSchema = if (this.inferSheetSchema) {
108	        val stringsAndCellTypes = sheet.rowIterator.asScala.drop(1).map(_.cellIterator.asScala.map(c => c.getCellType).toVector).toVector
109	        InferSchema(parallelize(stringsAndCellTypes), header.toArray)
110	      } else {
111	        // By default fields are assumed to be StringType
112	        val schemaFields = header.map { fieldName =>
113	          StructField(fieldName.toString, StringType, nullable = true)
114	        }
115	        StructType(schemaFields)
116	      }
117	      if (addColorColumns) {
118	        header.foldLeft(baseSchema) {(schema, header) => schema.add(s"${header}_color", StringType, nullable = true)}
119	      } else {
120	        baseSchema
121	      }
122	    }
123	  }
124	}

**Comment by nightscape** [comment]
Hi @bssulfikkar,

unfortunately I won't be able to help you with an issue description like this.
Can you read the following post and edit your issue description accordingly?
https://leantesting.com/write-good-bug-report/

**Comment by bssulfikkar** [comment]
Hi,

Could you confirm if the code is executed and loaded the data into a
dataframe .I am getting build error.I am new to scala hence kindly help me
out.

**Comment by bssulfikkar** [comment]
Hi,

I could fix the issue..but main is not included in the code...thanks
