### ISSUE TITLE
Is there a plan to support spark2.4?

### ISSUE THREAD

**Issue by ererermao** [crealytics/spark-excel#100]
Is there a plan to support spark2.4?

**Comment by surya-zemoso** [comment]
Is there a plan to support spark2.4?

**Comment by nightscape** [comment]
@ererermao happy to accept a corresponding pull request 😃 
@surya-zemoso your problem is not caused by Spark 2.4, but rather because parameters have changed.
Please read the README and CHANGELOG regarding `dataAddress`.

**Comment by surya-zemoso** [comment]
I tried again after removing sheetName. Now Its saying that "An error occurred while calling o71.load.
: java.lang.NoClassDefFoundError: org/apache/poi/ss/util/CellReference".

**Comment by nightscape** [comment]
@surya-zemoso this still seems unrelated to Spark 2.4. Can you create a new issue, following the guides from the issue template?

**Comment by surya-zemoso** [comment]
@nightscape I checked with scala and It is working fine. The problem was only with pyspark. I imported some required jars and now its working. Thank you :)

**Comment by nightscape** [comment]
Please try version `0.12.0` which has support for Spark 2.4.x (and Scala 2.12).
