### ISSUE TITLE
SheetName option not woking

### ISSUE THREAD

**Issue by nickreddy** [crealytics/spark-excel#101]
This my code:
  val rawfile = spark.read.format("com.crealytics.spark.excel")
    .option("sheetName", "edw")
   .option("useHeader", "true")
    .option("treatEmptyValuesAsNulls", "true")
    //.option("inferSchema", "true")
    .option("addColorColumns", "False")
    .load(inputPath)

Use case: I am trying to read one single tab from excel file and load it into df.

This is my build.sbt 
// https://mvnrepository.com/artifact/com.crealytics/spark-excel
libraryDependencies += "com.crealytics" %% "spark-excel" % "0.11.0"

Error message 
Exception in thread "main" scala.MatchError: Map(treatemptyvaluesasnulls -> true, path -> /Users/nick.narsaraopally/Documents/Z0lu.xlsx, useheader -> true, addcolorcolumns -> False, sheetname -> edw) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)

But when I change my build.sbt to 
// https://mvnrepository.com/artifact/com.crealytics/spark-excel
libraryDependencies += "com.crealytics" %% "spark-excel" % "0.10.2"

My code works as its suppose to work.

**Comment by nightscape** [comment]
Please read the README and CHANGELOG.
