### ISSUE TITLE
dataAddress option is not working

### ISSUE THREAD

**Issue by divasnikhra** [crealytics/spark-excel#103]
I am using Spark 2.0.x and Scala 2.11 with Spark Excel Library version 0.10.0. I also tried 0.11.0, 0.11.1 beta-3 but with all versions I am not able to select data based on  token provided in dataAddress.

Below token format I am using and my xlxs file is having only 1 sheet.
Token format which I tried
B3:F35
B3

**Comment by divasnikhra** [comment]
with 0.11.0 also I tried and its not working. I am getting the below error with 0.11.0

Exception in thread "main" scala.MatchError: Map(useheader -> true, path -> C:/Users/divash.nikhra/workspaceEDLTrunk/edl/edl-dt/src/test/resources/files/myTest.xlsx) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)

My Code is
 val sampleDF  = EdlSparkObjects.sparkSession.read
  .format("com.crealytics.spark.excel")
  //.option("sheetName", "Sheet1")
  .option("useHeader", "true")
  //.option("treatEmptyValuesAsNulls", "false")
  //.option("inferSchema", "false")
  .option("dataAddress", "B3:C4")
  //.option("excerptSize", 10)
  //.option("addColorColumns", "true")
  .load("C:/Users/divash.nikhra/workspaceEDLTrunk/edl/edl-dt/src/test/resources/files/myTest.xlsx")
  sampleDF.show()

**Comment by divasnikhra** [comment]
> dataAddress only works on 0.11 upwards.
> Moreover, could you provide the answers to the questions that should have appeared when you initially created the issue?

with 0.11.0 also I tried and its not working. I am getting the below error with 0.11.0

Exception in thread "main" scala.MatchError: Map(useheader -> true, path -> C:/Users/divash.nikhra/workspaceEDLTrunk/edl/edl-dt/src/test/resources/files/myTest.xlsx) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)

My Code is
val sampleDF = EdlSparkObjects.sparkSession.read
.format("com.crealytics.spark.excel")
//.option("sheetName", "Sheet1")
.option("useHeader", "true")
//.option("treatEmptyValuesAsNulls", "false")
//.option("inferSchema", "false")
.option("dataAddress", "B3:C4")
//.option("excerptSize", 10)
//.option("addColorColumns", "true")
.load("myTest.xlsx")
sampleDF.show()

**Comment by nightscape** [comment]
Something is wrong here because the dataAddress doesn't even show up in the options map. Can you try with pure Spark without EDL?

**Comment by nightscape** [comment]
Please try `0.12.0` and reopen if the problem persists.
