### ISSUE TITLE
null cells shift columns when `maxRowsInMemory` enabled

### ISSUE THREAD

**Issue by PanAeon** [crealytics/spark-excel#104]
When I specify `.option("maxRowsInMemory", 100)` then the empty cells are "skipped", for example:

| A         | B     | C          |
| --------- | ----- | ---------- |
| value     | b0    | c0         |
| **null**   | b1    | c1         |

without `maxRowsInMemory` second row would be read as `null | b1 | c1`.
But when I specify the option I get `null | c1 | null`.

Even when I just save the file again on mac the problem goes away, and I can't upload the original file.

I tried to set on/off `treatEmptyValuesAsNulls`, and tried different `maxRowsInMemory` values, but the problem persists.

## Environment:
* Spark 2.2.0
* Scala 2.11.8
* Spark-Excel  0.11.0
* environment: local[*]
* os macOS Sierra 10.12.6

**Comment by PanAeon** [comment]
I think there's a bug in the `excel-streaming-reader`. I'm sorry I can't make a reproducible file. 
A possible workaround is not to set `maxRowsInMemory`, but sometimes files can get really big, and this is not an option.

An apache poi contains `SXSSF` package which looks like a direct analogue of `excel-streaming-reader`. Do you think it's possible to migrate to the sxssf?

**Comment by PanAeon** [comment]
Related issue in `xlsx-streamer`: monitorjbl/excel-streaming-reader#181

**Comment by paulpaul1076** [comment]
Does anyone know when this will be fixed?

**Comment by PanAeon** [comment]
The fix is already merged into `excel-streaming-reader` once it gets released we can use that fix.

**Comment by paulpaul1076** [comment]
@PanAeon thanks!

**Comment by paulpaul1076** [comment]
@PanAeon do you know when they will release it though? We are using this library in production and it's frustrating that this doesn't work.

**Comment by PanAeon** [comment]
No, I had to build my own version to overcome this problem. I think sbt can
build a dependency from github, so we don't have to wait for the release,
but it sounds like too much hassle for me.

**Comment by paulpaul1076** [comment]
@PanAeon thanks for this info!

**Comment by ajaydubey777** [comment]
Hi @PanAeon,
I am getting error while using crealytics to read excel file of size 30 MB, were you abel to fix that issue and give some pointer
