### ISSUE TITLE
How to read an xlsx file having multiple sheets?

### ISSUE THREAD

**Issue by rashid-1989** [crealytics/spark-excel#107]
I have different excel files with multiple sheets in a directory. I am not sure about the sheet names.
How do I read/ Iterate over all the sheet names without providing the names explicitly.

**Comment by rashid-1989** [comment]
@nightscape Could you please suggest?

**Comment by nightscape** [comment]
I don't understand. Did you `sed` some characters in the `.xlsx` files? Those files are zipped, if you replace characters in them then with very high probability they're not valid zip files anymore...

**Comment by rashid-1989** [comment]
Yes, I had to because, while transferring files from windows to linux env, I am getting controlM characters in them and the code terminates with an exception due to that. Once i remove the ControlM characters and read, I am getting the above exception. Could you please suggest any better way of doing this as i need to get the files from windows everytime and suspect that it will contain the meta characters everytime i transfer. I am getting same even if i zip and get them on linux.

**Comment by rashid-1989** [comment]
And this is not the case with excel files with single sheet. Its happening with the ones having multiple sheets.

**Comment by rashid-1989** [comment]
My Bad! a quick correction here. There is no controlM problem. Its just the code is unable to read excel file from hdfs having mutiple sheets. I am able to read excel file with single sheet but not the other files with multiple sheets.

I am trying to create dataframes out of both the sheets separately. However, the code is able to read only one and skips the other one without exception.

Below is the code :

val file_df = sqlContext.read
          .format("com.crealytics.spark.excel")
          //.option("location", file)
          .option("dataAddress", "'Sheet1'!A1")
          .option("useHeader", "true")
          .option("treatEmptyValuesAsNulls", "true")
          .option("inferSchema", "true")
          .option("addColorColumns", "false")
          .option("maxRowsInMemory",20)
          .option("encoding","UTF-8")
          .load(hdfs_path)
        file_df.show()


val file_df2 = sqlContext.read
              .format("com.crealytics.spark.excel")
              //.option("location", file)
              .option("dataAddress", "'State2'!A1")
              .option("useHeader", "true")
              .option("treatEmptyValuesAsNulls", "true")
              .option("inferSchema", "true")
              .option("addColorColumns", "false")
              .option("maxRowsInMemory",20)
              .option("encoding","UTF-8")
               .load(hdfs_path)
            file_df2 .show()

**Comment by nightscape** [comment]
Your calls look correct. What do file_df1 and file_df2 contain after that?

**Comment by rashid-1989** [comment]
@nightscape I have updated the issue. Need your help!

**Comment by nightscape** [comment]
There's currently no way to list all sheet names. What you can do is to provide sheet numbers instead of sheet names. This will probably throw an exception if no sheet with that number exists (haven't tested), so you'd have to iterate over sheet numbers until an exception is thrown.

**Comment by rashid-1989** [comment]
Ok, The thing is I don't even have idea about which sheet to read and what name it has, because every time i receive files, they will contain sheets with different names. All i need to do is iterate over all the sheets to get those many Data frames and run spark sql to select columns out of them. Looks like i need to find out some other way to do this.
Thanks!

**Comment by nightscape** [comment]
That's why I mentioned you can use `sheet numbers` as well. You don't have to guess those, just take `0 until 20` and catch the exception.

**Comment by wanghhui** [comment]
@nightscape 
my excel usually contains 8+ worksheets, each contains 65535 rows. Only the first worksheet has a header.
I hope I can load all sheets into 1 dataframe, 
1. is there an option in dataAddress for loading all sheets?
2. In case I have to iterate all sheets: If my df loaded sheet1 already, how to load and append sheet2?

Many thanks in advance.

**Comment by nightscape** [comment]
Hi @wanghhui, you should be able to do something along the following lines:

1. Read the first sheet (with headers and infer column types) into `df`
2. Extract the schema using `val myCustomSchema = df.schema`
3. Read all other sheets using `spark.read.format("com.crealytics.spark.excel").option("dataAddress", s"$currentSheetNum!A1:Z65535").schema(myCustomSchema).load(...)`
4. Union all DataFrames: `val finalDf = dfsForSheets.foldLeft(df)(_ union _)`

Hope that helps.

**Comment by Sohail0489** [comment]
@nightscape Thank you so much, somehow managed to readthrough your answer, after spending time multiple times on other answers on this same page

**Comment by Sohail0489** [comment]
xyz

**Comment by Shankhadip96** [comment]
How to get the list of all the Sheet names ? Is there any way we can find ?

**Comment by quanghgx** [comment]
Hi @Shankhadip96 
 
Currently, spark-excel doesn't have an API to list the available sheet-names.
If you can use scala/java to access apache POI, it should be straightforward.
 
For spark-excel, its expected input is multiple excel files (result of glob pattern, for example), those might have different sets of sheet-names. We are still looking for a way to logically represent the sheet name (maybe through a dataframe.read API, with different options for loading type).

**Comment by Justinljg** [comment]
Hi any updates with regards to this issue? I am currently also facing the issue of dynamically referencing the sheet names.

**Comment by nightscape** [comment]
@Justinljg see my comment in https://github.com/crealytics/spark-excel/pull/196#issuecomment-1376972780 on how to (probably) get the sheet names from PySpark and this comment https://github.com/crealytics/spark-excel/issues/107#issuecomment-465978207 on how to read multiple sheets.
