### ISSUE TITLE
com.crealytics.spark.excel.DefaultSource does not allow create table as select

### ISSUE THREAD

**Issue by mdivk** [crealytics/spark-excel#110]
Hello,

We are using 
`spark2-shell --packages com.crealytics:spark-excel_2.11:0.8.2`

Code is here:

```
var df = spark.sql(q)
println("df.count=" + df.count)
println("sheet:" + line)
df.write.format("com.crealytics.spark.excel").option("dataAddress", "'" + line + "'!A1").option("useHeader", "true").mode("append").save(excel_file + ".xlsx")
```
From the output I see df.count is correct, but when writing the df to excel, here is the error message:

> processing: ah01_branch_grouped_by_month
> select * from v201812_ah01_branch_grouped_by_month
> df.count=419
> sheet:ah01_branch_grouped_by_month
> java.lang.RuntimeException: com.crealytics.spark.excel.DefaultSource does not allow create table as select.
>   at scala.sys.package$.error(package.scala:27)
>   at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:476)
>   at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
>   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
>   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
>   at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
>   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
>   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
>   at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
>   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
>   at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
>   at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
>   at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
>   at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
>   at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
>   at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
>   at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
>   at $anonfun$1.apply(<console>:41)
>   at $anonfun$1.apply(<console>:34)
>   at scala.collection.Iterator$class.foreach(Iterator.scala:893)
>   at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
>   ... 58 elided

it would be greatly appreciated if anyone can help me sort it out as early as possible, thank you.

**Comment by nightscape** [comment]
Duplicate of https://github.com/crealytics/spark-excel/issues/106.
Why are you still using `0.8.2`? `0.11.0` is the newest version and it supports writing.

**Comment by mdivk** [comment]
Thank you, working now.
