### ISSUE TITLE
Add Support for FTP file read

### ISSUE THREAD

**Issue by ramvodedara** [crealytics/spark-excel#112]
Currently there is no support for FTP file read

**Comment by nightscape** [comment]
We're open to PRs :smiley:

**Comment by juarezr** [comment]
Maybe loading/writing from http/ftp should be developed for all Spark data formats, not only spark-excel. Currently there are drivers for `file://`, `hdfs://`, `s3://`, `jdbc://`.

Alternatively it's possible load like in this [example](https://stackoverflow.com/questions/57014043/reading-data-from-url-using-spark-databricks-platform):

``` python
url = "https://raw.githubusercontent.com/thomaspernet/data_csv_r/master/data/adult.csv"
from pyspark import SparkFiles
spark.sparkContext.addFile(url)

df = spark.read.csv("file://"+SparkFiles.get("adult.csv"), header=True, inferSchema= True)
```

Considering these points, should this issue be closed?

**Comment by nightscape** [comment]
@juarezr yes, I think there's not much we can do here.
It might even be possible already, but can't tell for sure:
https://github.com/apache/hadoop/blob/a55d6bba71c81c1c4e9d8cd11f55c78f10a548b0/hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/TestDelegateToFileSystem.java
