### ISSUE TITLE
Can we get the excel row number column while reading Excel file to the dataframe? 

### ISSUE THREAD

**Issue by donthusa** [crealytics/spark-excel#115]

**Comment by quanghgx** [comment]
Hi @donthusa,
Please help check the spark-excel 0.14.0 (and up) with the new row_number column option.
Feel free to reopen this ticket in case of further issue.
Sincerely,

**Comment by monofish** [comment]
Hi, @quanghgx 

Just wondering if spark-excel 0.14.0 really ships with Scala 2.11 or it is in the plan? It is showed on the project [README](https://github.com/crealytics/spark-excel#scala-211). However, I cannot find it in Maven public repo but 0.13.7 with Scala 2.11 and 0.14.0 with Scala 2.12.
Really need this `row_number` column feature. Thanks.

**Comment by quanghgx** [comment]
Hi @monofish 
 
You are right, spark-excel 0.14.0 doesn't have the scala 2.11 binaries in public repositories, yet. I've just created a ticket for tracking here https://github.com/crealytics/spark-excel/issues/426
In the meantime, how about building a local binary from spark-excel source for scala 2.11 and your version of spark?
