### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: Failed to find data source: com.crealytics.spark.excel. Please find packages at http://spark.apache.org/third-party-projects.html

### ISSUE THREAD

**Issue by krishnan1997** [crealytics/spark-excel#116]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
> If you're describing a bug, tell us what should happen
> If you're suggesting a change/improvement, tell us how it should work

## Current Behavior
> If describing a bug, tell us what happens instead of the expected behavior
> If suggesting a change/improvement, explain the difference from current behavior.
> If you have a stack trace or any helpful information from the console, paste it in its entirety.
> If the problem happens with a certain file, upload it somewhere and paste a link.

## Possible Solution
> Not obligatory, but suggest a fix/reason for the bug,
> or ideas how to implement the addition or change

## Steps to Reproduce (for bugs)
> Provide a link to a live example, or an unambiguous set of steps to
> reproduce this bug. Include code to reproduce, if relevant
1. E.g. clone repository xyz with minimal code for reproduction
2. E.g. package JAR using Maven with the following POM
3. E.g. command you used to start Spark (`spark-submit --foo=bar ...`)
4. ...

## Context
> How has this issue affected you? What are you trying to accomplish?
> Providing context helps us come up with a solution that is most useful in the real world

## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version and language (Scala, Java, Python, R, ...):
* Spark-Excel version:
* Operating System and version, cluster environment, ...:

**Comment by krishnan1997** [comment]
My build.sbt
val sparkVersion = "2.2.1"
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
  "com.crealytics" %% "spark-excel" % "0.8.3",
  "org.apache.spark" %% "spark-mllib" % sparkVersion % "provided")

Main.scala

val sqlContext = new SQLContext(sc)
    val df = sqlContext.read
    .format("com.crealytics.spark.excel")
    .option("useHeader", "true")
    .option("treatEmptyValuesAsNulls", "true")
    .option("inferSchema", "true")
    .option("addColorColumns", "False")
    .load("myfile.xlsx")

**Comment by nightscape** [comment]
Why are you using such an outdated version?

**Comment by nightscape** [comment]
`0.12.0` is the newest version, please try again with that one.

**Comment by khaulaAhmad** [comment]
I am using the latest version with spark-excel_2.12-0.13.1.jar but still facing the same error.
