### ISSUE TITLE
Not reading the specified Sheet other than the first one in the file

### ISSUE THREAD

**Issue by skybutter** [crealytics/spark-excel#118]
No matter what sheetName is specified in the .option("sheetName") it always read the first Excel Sheet in the file.
## Expected Behavior
Read from the specified sheet in the Excel file when specified sheetName in option.

val empFile = "C:\\EmpDatasets.xlsx"

val employeesDF = sc.sqlContext.read
  .format("com.crealytics.spark.excel")
  .option("sheetName", "Sheet2")
  .option("useHeader", "true")
  .option("treatEmptyValuesAsNulls", "false")
  .option("inferSchema", "false")
  .option("location", empFile)
  .option("addColorColumns", "False")
  .load()

employeesDF.createOrReplaceTempView("EMP")

## Current Behavior
No matter what "sheetName" is specified, always return the first sheet in the file.
Even if specifying a sheet name that do not exist, always return the first sheet.

## Context
I have Excel files that have multiple work sheets.  I need to read from all of them.

## Your Environment
* Spark version = 2.4
Using Scala
* Spark-Excel version: com.crealytics:spark-excel_2.11:0.11.1
* Operating System and version, cluster environment: running on AWS

**Comment by Kaldie** [comment]
The changelog describes that the sheetname param is removed and that dataAddress option should be used. Would give that a go
