### ISSUE TITLE
org/apache/poi/ss/util/CellReference

### ISSUE THREAD

**Issue by Orhanyildirim** [crealytics/spark-excel#120]
I have Spark 2.4 since 2 months and i can no more use spark-excel Issue: java.lang.NoClassDefFoundError: org/apache/poi/ss/util/CellReference
Do you have any idea?

**Comment by nightscape** [comment]
Can you fill the issue template that should have appeared when you created the issue?

**Comment by nightscape** [comment]
Can you try with `0.12.0` and reopen this issue with more details if it persists?
