### ISSUE TITLE
Main method not found in class com.crealytics.spark.excel.WorkbookReader

### ISSUE THREAD

**Issue by divasnikhra** [crealytics/spark-excel#121]
I tried to build this project using below command

sbt run
&
sbt "runMain com.crealytics.spark.excel.WorkbookReader"

But unfortunately getting error 

[info] Running (fork) com.crealytics.spark.excel.WorkbookReader
[error] Error: Main method not found in class com.crealytics.spark.excel.WorkbookReader, please define the main method as:
[error]    public static void main(String[] args)
[error] or a JavaFX application class must extend javafx.application.Application
[error] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048M; support was removed in 8.0
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 11 s, completed Apr 10, 2019 7:28:43 PM

So, I tried to search Main file in the project. But I didn't get its entry point.
Can you please help me in solving this issue, As I am new to SBT

**Comment by nightscape** [comment]
This project is a Spark plugin, not a standalone executable.
Please use it as specified in the README :stuck_out_tongue_winking_eye:
