### ISSUE TITLE
empty column names not supported

### ISSUE THREAD

**Issue by benwbooth** [crealytics/spark-excel#122]
Trying to open a spreadsheet with an empty column name causes and exception to be thrown. Normally, spark would add default column names like `_c0`, `_c1`, etc. Actually, if you run `df.columns`, you can see that spark added the default column names to the DataFrame, but trying to access them throws an exception.

Another related issue is that column renaming using `.toDF()` does not work. This is due to this code in ExcelRelation.scala starting at line 34:

```
  lazy val columnIndexForName = if (useHeader) {
    headerCells.map(c => c.getStringCellValue -> c.getColumnIndex).toMap
  } else {
    schema.zipWithIndex.map { case (f, idx) => f.name -> idx }.toMap
  }
```

I think the code should always look at the schema for the column names. Initially, the schema's column names should be extracted from the header row if useHeader is true, but after that, the schema should be where column names are looked up.

Here is the exception:

```
@ plate2.select("_c0").show()
java.util.NoSuchElementException: key not found: _c0
  scala.collection.MapLike$class.default(MapLike.scala:228)
  scala.collection.AbstractMap.default(Map.scala:59)
  scala.collection.MapLike$class.apply(MapLike.scala:141)
  scala.collection.AbstractMap.apply(Map.scala:59)
  com.crealytics.spark.excel.ExcelRelation.com$crealytics$spark$excel$ExcelRelation$$columnExtractor(ExcelRelation.scala:58)
  com.crealytics.spark.excel.ExcelRelation$$anonfun$5.apply(ExcelRelation.scala:74)
  com.crealytics.spark.excel.ExcelRelation$$anonfun$5.apply(ExcelRelation.scala:74)
  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
  com.crealytics.spark.excel.ExcelRelation.buildScan(ExcelRelation.scala:74)
  org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:300)
  org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:300)
  org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:326)
  org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:325)
  org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:403)
  org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:321)
  org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:296)
  org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
  scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
  scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
  org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
  org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
  scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  scala.collection.Iterator$class.foreach(Iterator.scala:891)
  scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
  scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
  org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
  org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
  scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
  scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
  org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:72)
  org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:68)
  org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:77)
  org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:77)
  org.apache.spark.sql.Dataset.withAction(Dataset.scala:3360)
  org.apache.spark.sql.Dataset.head(Dataset.scala:2545)
  org.apache.spark.sql.Dataset.take(Dataset.scala:2759)
  org.apache.spark.sql.Dataset.getRows(Dataset.scala:255)
  org.apache.spark.sql.Dataset.showString(Dataset.scala:292)
  org.apache.spark.sql.Dataset.show(Dataset.scala:746)
  org.apache.spark.sql.Dataset.show(Dataset.scala:705)
  org.apache.spark.sql.Dataset.show(Dataset.scala:714)
  ammonite.$sess.cmd11$Helper.<init>(cmd11.sc:1)
  ammonite.$sess.cmd11$.<init>(cmd11.sc:7)
  ammonite.$sess.cmd11$.<clinit>(cmd11.sc)
```

**Comment by nightscape** [comment]
Atm, I don't have much time to improve this. Would you be willing to look into this and create a PR?

**Comment by Klunio** [comment]
@benwbooth have you solved the problem? I'm begging for the solution

**Comment by nightscape** [comment]
@Klunio thanks for opening a PR! In order to better understand what you're trying to do, could you give more details, [as specified in the issue template](https://github.com/crealytics/spark-excel/blob/c613b4b5966a2acc5a3ea7b745848bff4526bd33/ISSUE_TEMPLATE.md)?

@benwbooth you already explained your issue partially, but I still have some questions:

1. Are you trying to `useHeader` and specify a custom schema? Or were you trying to use a custom schema as workaround to not being able to `useHeader`?
2. Do you want to have all headers be read from the first line, but if one cell is empty it should get a name like `_c5`?

**Comment by Klunio** [comment]
#139 
@nightscape Problems happen when I load files with `usrHeader` set `true`.

In File `ExcelRelation.scala`, I notice that `cellExtractor` extracts data according to `columnIndex` which comes from the Map `columnIndexForName`.

Like the following example, 

col_1 |   | col_2
-- | -- | --
a |   | d
b |   | e
c |   | f

The problem results from `columnIndexForName`. I don't know when it is firstly used and generated but definitely before the calling of function `makeSafeHeader`, which names the second column `_c2`.

`columnIndexForName` would not update the new field information, thus when extracting data and  mapping the key value `_c2`, it failed.

Also, it failed while there are duplicated col names for the header changes again and `columnIndexForName` dose not update.


### solution

I did not know the right way fixing this issue, all I did is filter the empty col name and reload `columnIndexForName` everytimes after calling `makeSafeHeader`.

**Comment by AyubmmD** [comment]
Was this issue fixed? I tried loading an Excel with an empty header field. It threw me an exception  "java.util.NoSuchElementException: key not found: _c0 ".

[TestFile.xlsx](https://github.com/crealytics/spark-excel/files/3665143/TestFile.xlsx)

**Comment by nightscape** [comment]
I've changed the logic to handle empty columns in `0.12.2`.
Can you give that a try and see if it works?

**Comment by AyubmmD** [comment]
Hi @nightscape , Seems like it ignores that column altogether. Attaching a screenshot for that. Anyways I was able to use workaround (custom schema) and get my requirement done.

<img width="520" alt="issue" src="https://user-images.githubusercontent.com/13267258/66254938-f2714480-e79a-11e9-8230-a6c21075e4ee.PNG">

**Comment by Pranith1785** [comment]
Hi @AyubmmD ,
could you help with schema creation for above scenario, where no columns

**Comment by AyubmmD** [comment]
Hi @Pranith1785  , not sure what you are asking here. 
   You have a empty header field like my [testfile ](https://github.com/crealytics/spark-excel/files/3665143/TestFile.xlsx)  and want to add the column name for that column manually ? 
   I don't think that is possible at-least with the version 0.12.2.    The current behavior (0.12.2) is that when you load the excel with the empty header field, it will  ignore that column itself, like shown in my above comment.
If latest version of crealytics  supports that I am not sure.  @nightscape

**Comment by Pranith1785** [comment]
Thanks @AyubmmD ...i will create column names and do it

**Comment by Mrrobot2709** [comment]
Hi in version 13+ we can not use null headers kindly resolve it as as it was in 12.0 when inferSchema set to false it takes all collumn including empty headers .
My source data type
kindly help @nightscape 
![image](https://user-images.githubusercontent.com/40589697/91147993-a4c53980-e6d6-11ea-93ca-86e986b17b6c.png)

**Comment by Mrrobot2709** [comment]
with 13.5 
![image](https://user-images.githubusercontent.com/40589697/91148100-cde5ca00-e6d6-11ea-8d42-1d86646b2cd5.png)

with 12.0 
![image](https://user-images.githubusercontent.com/40589697/91148174-e81fa800-e6d6-11ea-9676-43d97c467463.png)

Kindly update it with 13+ versions as many things got imporoved kindly add this functionality with 13+

**Comment by Mrrobot2709** [comment]
HI while reading excel it don't read null header in version13+ while in version 12 it reades null headers too

in Version 12+
when we set inferScheama False 
![image](https://user-images.githubusercontent.com/40589697/91153213-8d3d7f00-e6dd-11ea-84ed-cc11b4968593.png)

in Version 13 +
![image](https://user-images.githubusercontent.com/40589697/91153315-ae9e6b00-e6dd-11ea-809b-36a05e7ad77f.png)

kindly help @nightscape @@fthomas bec in new upgrade lots things improved kinldy correct this feature too
My Data is machine generated and lots of files so manual procedure can't be done

My source Data
![image](https://user-images.githubusercontent.com/40589697/91153509-ef967f80-e6dd-11ea-8233-add371640efa.png)

**Comment by nightscape** [comment]
Can you try manually specifying the `dataAddress` to read exactly the address range you require (see the Readme)?

**Comment by Mrrobot2709** [comment]
Yes i can but in that case Headers will be lost .
If you fix this bug that will make your package more stability as this is the only package available in pyspark to read Excel Files so it will be helpful for other developers too  .
Thanks @nightscape

**Comment by nightscape** [comment]
@Mrrobot2709 I would recommend reading the data in two steps, first the metadata part in the upper rows and then the data in the lower rows.
If you want to read it in one swoop, try specifying a data address like `A1:ZZ9999`. That might help in getting all columns instead of only the ones containing values in the first rows.

**Comment by Mrrobot2709** [comment]
Same Issue with this 
@nightscape 
![image](https://user-images.githubusercontent.com/40589697/91685294-90ba8580-eb77-11ea-9a42-951b00610b4b.png)

CODE IMAGE :-
![image](https://user-images.githubusercontent.com/40589697/91685324-a2039200-eb77-11ea-940a-bb47a2f1ac85.png)

**Comment by nightscape** [comment]
Ok, can you try using `A6:ZZ99999` (if A6 is the cell where the real table data begins)?

**Comment by mukheshnarra** [comment]
@nightscape i am facing same issue. even i tried with giving full schema and placing data Address as A:ZZ99999

**Comment by nightscape** [comment]
Hi @mukheshnarra, could you create a new issue, following the steps from the [issue template](https://github.com/crealytics/spark-excel/blob/master/ISSUE_TEMPLATE.md) that should hopefully be shown?
This issue has changed so much over time that it's hard to guess what's really the problem.
