### ISSUE TITLE
Exception in thread “main” scala.MatchError:Map() (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)

### ISSUE THREAD

**Issue by jagadeesh427** [crealytics/spark-excel#123]
I am trying load the data from excel sheet to hive table. I am geting below error .Map(treatemptyvaluesasnulls -> true, location -> "input", useheader -> true, inferschema -> true, addcolorcolumns -> false, sheetname ->"INPUT") (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)

code used:
 val df = spark.read.format("com.crealytics.spark.excel")
      .option("location", tname)
      .option("sheetName", fname)
      .option("useHeader", "true")
      .option("treatEmptyValuesAsNulls", "true")
      .option("inferSchema", "true")
      .option("addColorColumns", "false")
      .load()
    //df.printSchema()
    //df.show(100)
    df.createOrReplaceTempView(s"""$fname""")

## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version and language (Scala, Java, Python, R, ...):  <spark.version>2.2.0.cloudera2</spark.version>
        <scala.version>2.11.8</scala.version>
* Spark-Excel version:
 <groupId>com.crealytics</groupId>
            <artifactId>spark-excel_2.11</artifactId>
            <version>0.11.0-beta3</version>
* Operating System and version, cluster environment, ...:

**Comment by nightscape** [comment]
Can you try with `0.11.1` and post the full output from the command line?
