### ISSUE TITLE
Excel Formula and formatting

### ISSUE THREAD

**Issue by Kartik-RTP** [crealytics/spark-excel#124]
Hi , I am trying to use spark-sql to generate some reports.
I would like to know if there is any way top to push excel formulas and set cell formatting using spark-excel. I am creating a sheet dynamically where number of rows is not known at start , hence i can't pre-style an empty sheet and then write into it. Also , I want to apply some excel formulas on the given columns at the end where again row number is not known at start. I know Apache POI is a lower level api and maybe supporting these operations but then i wanted to check if excel formatting and formulas can be used through spark-excel itself .

**Comment by nightscape** [comment]
Hi @Kartik-RTP, currently there is no support for writing formulas or coloring cells.
If you're familiar with Scala, we would be very open to a PR though :smiley:

**Comment by Kartik-RTP** [comment]
hi @nightscape  .thanks for your quick reply...Unfortunately , at this point ,I believe  I am not experienced enough to work on this kind of change..Once i am able to get some familiarity with Apache POI , I might come back to give this change a try

**Comment by quanghgx** [comment]
Hi @Kartik-RTP and Martin,

Would like to close this ticket, however feel free to reopen it.
Sincerely,
