### ISSUE TITLE
Reading Excel data from memory

### ISSUE THREAD

**Issue by julianblack** [crealytics/spark-excel#141]
Does this library support a direct read from memory or does it have to be an Excel file on disk? I'm downloading an Excel file from a web API call and have the contents in memory.  Works successfully if I write to disk but would rather avoid it.  Really appreciate any help!

**Comment by nightscape** [comment]
That is currently not possible, but we're open to PRs :wink:

**Comment by quanghgx** [comment]
It seems no plan of supporting this.
Going to close this ticket.
