### ISSUE TITLE
Incorrect datatype on Integer type column

### ISSUE THREAD

**Issue by NiharGharat** [crealytics/spark-excel#162]
Your issue may already be reported!

I was looking at this issue https://github.com/crealytics/spark-excel/issues/33
And was wondering is it resolved in latest spark excel 0.12.3.

## Expected Behavior
> Integer column xlsx should produce integerType datatype and value should not have been affected.
> inferSchema - false correctly gets all as String; but true causes the problem

## Current Behavior
> Integer column get inferred as Double datatype with zero appended eg - <value>.0
[testFileXlsx.xlsx](https://github.com/crealytics/spark-excel/files/3789084/testFileXlsx.xlsx)

## Steps to Reproduce (for bugs)
These are the options used
sparkSession.read().format("com.crealytics.spark.excel")
					.option("dataAddress", "'" + sheetNameToPrase + "'!A1").option("useHeader", true)
					.option("location", filePath).option("treatEmptyValuesAsNulls", true)
					.option("inferSchema", true).option("addColorColumns", "false")
					.load(filePath);

## Your Environment
>Spark version 2.4.4 scala 2.11 java 8
>Spark-excel - 0.12.3 scala 2.11

**Comment by NiharGharat** [comment]
Hi @nightscape, thanks for the reply. I am not familiar to Scala hence won't be able to contribute. I will go ahead and close the issue.

**Comment by nightscape** [comment]
We can leave it open as it hasn’t been solved.

**Comment by quanghgx** [comment]
Hi @NiharGharat 
Thank you so much for your detailed description and sharing the testFileXlsx.xlxs.

Please take a try again with spark-excel v0.14.0 (and up)? It has stricter numerical types (Integer, Long and Double) supports.
Going to resolve this ticket, however, feel free to reopen it in case of further issue.

Sincerely,

**Comment by bakhortech** [comment]
@quanghgx I am also facing similar issue but the scala version in my environment is 2.11 and moving to 2.12 is not feasible for me. I don't see spark-excel v0.14.0 (and up) is released for scala version 2.11. Is there any plan for releasing it for scala 2.11 as well? Please help me out here.

**Comment by nightscape** [comment]
We upgraded Spoiwo to a newer version which doesn't support Scala 2.11 anymore.
If you're tech-savvy enough, you could try to create a version with down-graded Spoiwo (and probably also POI).
