### ISSUE TITLE
Unable to read Any sheets after the first one in Excel file

### ISSUE THREAD

**Issue by gajendravaradhan** [crealytics/spark-excel#166]
Trying to load an Excel Workbook with multiple sheets named Location,Product,Account,LOB in that order
This is the snippet I am using,
public Dataset<Row> loadExcel(String path,String sheetName){
        return this.getSession().read()
                .format("com.crealytics.spark.excel")
                .option("sheetName", sheetName)
                .option("useHeader", "true")
                .option("treatEmptyValuesAsNulls", "true")
                .option("inferSchema", "true")
                .option("addColorColumns", "False")
                .load(path);
    }

I am trying to cycle through all the sheets and read data, everytime I am seeing that only the first sheet(Location) is getting read. Attaching my file.
[primary_to_secondary_mapping.xlsx](https://github.com/crealytics/spark-excel/files/3826747/primary_to_secondary_mapping.xlsx)

**Comment by tintinmj** [comment]
Having the exactly same issue. Any solution?

**Comment by gajendravaradhan** [comment]
Nope. Still waiting for a response here

**Comment by gajendravaradhan** [comment]
Created a StackOverflow question here, with my work-around: https://stackoverflow.com/questions/59220428/spark-excel-unable-to-read-any-sheets-after-the-first-one-in-excel-workbook

**Comment by tintinmj** [comment]
Actually there is a solution. https://github.com/crealytics/spark-excel/issues/118 :)

**Comment by quanghgx** [comment]
Hi @gajendravaradhan , please use `dataAddress` option
Thanks to @tintinmj
