### ISSUE TITLE
Read mutiple sheets with the same schema in spark

### ISSUE THREAD

**Issue by yuzhangyi** [crealytics/spark-excel#176]
It seems like that I cannot read multiple sheets from one excel with the same schema in spark? Do we have any way to support it?

spark.read.format("com.crealytics.spark.excel").option("useHeader", "true").option("inferSchema", "false").option("dataAddress", "test01!A1").option("dataAddress", "test04!A1").load("wasbs://mycontainer@zhanyu2016.blob.core.windows.net/test1213.xlsx")

It only read the schema and data of sheet 'test04', in my case, the "test01" and test "test04" has the same schema.

**Comment by nightscape** [comment]
The dataAddress options you provide override each other. You need to do multiple reads instead.

**Comment by yuzhangyi** [comment]
> The dataAddress options you provide override each other. You need to do multiple reads instead.

As I know, 'sheetName' is not supported in spark_excel_2.12, so I had to use 'dataAddress' to work around it to have ability to load other sheet's data. Is it possible to support multiple sheetName as options? for example spark.read.format("com.crealytics.spark.excel").option("useHeader", "true").option("sheetName", "test01").option("sheetName", "test02")....

**Comment by nightscape** [comment]
The parameters passed to the `.option(..., ...)` calls will override each other, as Spark creates a `Map[String, String]` out of them and passes it as such:
https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/DefaultSource.scala#L24
You could in theory come up with a String format that allows you to encode multiple sheet names into one option, but I'm not sure if it's worth the effort.
Personally, I would just do something like this:
```scala
val fileName = "wasbs://mycontainer@zhanyu2016.blob.core.windows.net/test1213.xlsx"
def readSheet(sheetName: String) = spark.read.csv(header = true, inferSchema = true, dataAddress = s"$sheetName!A1")
val data = Seq("test01", "test04").map(readSheet).reduce(_ union _)
```

**Comment by quanghgx** [comment]
1+ with Martin about the approach of using data frame union for this case.
Going to resolve this ticket.
