### ISSUE TITLE
Cannot read sheet which has empty columns in spark

### ISSUE THREAD

**Issue by yuzhangyi** [crealytics/spark-excel#177]
In my sheet, it has serval rows and columns "TIMESTAMP, Tenent, Role, ScaleUnit" while it has empty columns, when I use spark-excel to read this sheet, error is happened:

root
 |-- TIMESTAMP: timestamp (nullable = true)
 |-- _c1: string (nullable = true)
 |-- Tenant: string (nullable = true)
 |-- Role: string (nullable = true)
 |-- _c4: string (nullable = true)
 |-- ScaleUnit: string (nullable = true)
java.util.NoSuchElementException: key not found: _c1

The column "_c1" and "_c4" is auto generated by spark-excel. Can we support set the value to be "null" for all empty columns without error?

**Comment by quanghgx** [comment]
Hi @yuzhangyi 
Spark-excel should be able to handle columns with empty header by now. (September 3rd, 2021).
 
If it's possible, please help share your excel file or provide a little bit more description about it. I tried to reproduce the excel file from my side, however, the description lacks enough detail.
 
Given that this ticket is almost 2 years old now, just hope that, by any chance, you noticed this comment and help reopen this ticket with a little more detail.
Sincerely,
