### ISSUE TITLE
ExcelFileSaver.toCell() doesn't handle null values in DataFrame

### ISSUE THREAD

**Issue by slehan** [crealytics/spark-excel#18]
When a `DataFrame` row has a null value in one of the columns, a `scala.MatchError` exception gets thrown by `toCell`. I am writing with the following `write` calls:

```
    dataFrame.write
      .format("com.crealytics.spark.excel")
      .option("sheetName", config.sheetName)
      .option("treatEmptyValuesAsNulls", true)
      .option("useHeader", true)
      .mode("overwrite")
      .save(config.path)
```

This is reproducible by loading in an Excel or CSV file with blanks in any of the columns and attempting to save it. I added the `treatEmptyValuesAsNulls` just to make sure I wasn't missing an option but looking at the code it seems that a case needs to be added to handle if `a == null`. It is also possible I'm doing something wrong here, and if so, I apologize!

**Comment by nightscape** [comment]
No, you're not doing anything wrong and your diagnose is correct: The `toCell` method does not handle `null` yet https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/ExcelFileSaver.scala#L28-L40
Do you dare creating a PR for this?

**Comment by slehan** [comment]
I'll take a look at it today and see if I can't fix it!

**Comment by slehan** [comment]
@nightscape can we just assume that if it's null, we can just write an empty string to the Excel spreadsheet?

**Comment by nightscape** [comment]
You might want to use [`Cell.Empty`](https://github.com/norbert-radyk/spoiwo/blob/master/src/main/scala/com/norbitltd/spoiwo/model/Cell.scala#L28) in that case.
Currently that's the same as an empty string, but we'd be on the safe side if they decide to change that at one point.

**Comment by nightscape** [comment]
Closed by https://github.com/crealytics/spark-excel/pull/20
Version 0.9.1 should be on Maven central within a few hours.
