### ISSUE TITLE
Cannot read/load folder in spark

### ISSUE THREAD

**Issue by yuzhangyi** [crealytics/spark-excel#185]
Today when I try to load one folder which contains many excel files, it is not supported in current spark_excel, can we support it?

Example: spark.read.format("com.crealytics.spark.excel").option("useHeader", "true").option("inferSchema", "true").load("wasbs://inputdata@adfdataflowtest.blob.core.windows.net/data/excel")

Error: java.io.FileNotFoundException: wasbs://inputdata@adfdataflowtest.blob.core.windows.net/data/excel is a directory not a file.

**Comment by yuzhangyi** [comment]
> Today when I try to load one folder which contains many excel files, it is not supported in current spark_excel, can we support it?
> 
> Example: spark.read.format("com.crealytics.spark.excel").option("useHeader", "true").option("inferSchema", "true").load("wasbs://inputdata@adfdataflowtest.blob.core.windows.net/data/excel")
> 
> Error: java.io.FileNotFoundException: wasbs://inputdata@adfdataflowtest.blob.core.windows.net/data/excel is a directory not a file.

**Comment by yuzhangyi** [comment]
**Scenario**: It has one folder which contains multiple excel files (for example, test01.xlsx, test02.xlsx, test03.xlsx...), now the customer wants to load/read data with sheetName "sheet01" from all up excel files. The spark_excel will try to read data with sheetName "sheet01" from test01.xlsx, test02.xlsx... one by one, if the schema is different compared with first one, the remaining read will fail directly with error "schema is inconsistent among different excel files". If the schema of sheet01 is the same in all up excel files, we merge and return all data to customers.

**Question**: Can I help to add up function in spark_excel if no one does it recently? If yes, can you help share the process that I need to follow? Thanks!

**Comment by nightscape** [comment]
@yuzhangyi I have worked on code to do this:
https://github.com/crealytics/spark-excel/pull/153
Unfortunately, some tests are still failing and I haven't had time to fix everything.
You can try to build the PR locally and see if it works for you.

**Comment by yuzhangyi** [comment]
> @yuzhangyi I have worked on code to do this:
> #153
> Unfortunately, some tests are still failing and I haven't had time to fix everything.
> You can try to build the PR locally and see if it works for you.

Thanks for your information, @nightscape , I will have a try.

**Comment by wenyangchou** [comment]
How can I use it .   Would you give me a demo if you tried succeed

**Comment by burbeci** [comment]
Hey,
It might be obvious, but if performance is not a concern, you can use a workaround like this for the time being (written in python but should be easy to translate to other languages):
```python
#schemaOfSheets should be the schema of the XLS files. 

from pyspark.sql.dataframe import DataFrame
def get_dir_content(ls_path):
  dir_paths = dbutils.fs.ls(ls_path)
  subdir_paths = [get_dir_content(p.path) for p in dir_paths if p.isDir() and p.path != ls_path]
  flat_subdir_paths = [p for subdir in subdir_paths for p in subdir]
  return list(map(lambda p: p.path, dir_paths)) + flat_subdir_paths


def read_xls_as_df(fileName) -> DataFrame:
  return (spark.read
          .format("com.crealytics.spark.excel")
          .option("treatEmptyValuesAsNulls", "true") 
          .option("header", "true")
          .option("recursiveFileLookup", "true")
          .schema(schemaOfSheets)
          .load(fileName))

def read_xls_folder(path) -> DataFrame:
  currentDf = None
  for path in get_dir_content(path):
    if(currentDf == None):
      currentDf = read_xls_as_df(path)
    else:
      currentDf = currentDf.union(read_xls_as_df(path))
```

**Comment by quanghgx** [comment]
Hi @yuzhangyi, @wenyangchou and @burbeci 

Thank you so much for your detailed description. I totally agree, data frame union should work!
From spark-excel 0.14.0 (and up), it natively supports this feature. There is an [example in wiki](https://github.com/crealytics/spark-excel/wiki/Examples:-Load-Multiple-Files) as well.
Please help take a look when you have time.
Sincerely,

**Comment by quanghgx** [comment]
Going to close this ticket. Feel free to reopen it in case of further issues.
