### ISSUE TITLE
Contributions welcome: Auto-publish PRs

### ISSUE THREAD

**Issue by nightscape** [crealytics/spark-excel#186]
## Expected Behavior
Releasing new builds should be done by a CI service. In the best case, branches and PRs get built and published automatically to a specially named version, so that contributors can have their changes tested easily.

## Current Behavior
Releasing is done manually on a local developer machine. PR authors have to publish their branches in custom repositories. Users have to do extra configuration to use such repositories.

## Possible Solution
Use GitHub actions and sbt-ci-release-early for publishing.

Contributions are very welcome!

**Comment by nightscape** [comment]
Started implementation in https://github.com/crealytics/spark-excel/pull/189

**Comment by quanghgx** [comment]
Hi @nightscape , look like this issue is already addressed in https://github.com/crealytics/spark-excel/pull/189
I would like to resolve this ticket, feel free to reopen it otherwise.
