### ISSUE TITLE
Out of memory exception when reading big xlsx file

### ISSUE THREAD

**Issue by aprasa02** [crealytics/spark-excel#19]
I am reading big xlsx file of 100mb with 28 sheets(10000 rows per sheet) and creating a single dataframe out of it . I am facing out of memory exception when running on cluster mode .My code looks like this.

def buildDataframe(spark: SparkSession, filePath: String, requiresHeader: Boolean): DataFrame = {

    var excelDF: DataFrame = null
    var flag: Boolean = false
// getting inputstream from s3 for all sheet names   
 val s3FilePath = filePath.replaceAll(filePath.substring(0, filePath.indexOf("//") + 2), "")
    val s3Bucket = s3FilePath.substring(0, s3FilePath.indexOf("/"))
    val s3key = s3FilePath.substring(s3FilePath.indexOf("/") + 1, s3FilePath.length())
    val s3Client: AmazonS3 = new AmazonS3Client();
    val s3object: S3Object = s3Client.getObject(new GetObjectRequest(
      s3Bucket, s3key));
    val inputStream: java.io.InputStream = s3object.getObjectContent()
    val workbook = new XSSFWorkbook(inputStream)
    var sno = workbook.getNumberOfSheets
    var sheetName: Array[String] = new Array[String](sno)
    for ((sheet, i) <- workbook.zipWithIndex) {
      val initialDF = spark.read.format("com.crealytics.spark.excel")
        .option("useHeader", requiresHeader)
        .option("treatEmptyValuesAsNulls", "true")
        .option("inferSchema", true)
        .option("addColorColumns", false)
        .option("sheetName", sheet.getSheetName)
        .option("path", filePath)
        .load()

      if (flag == false) {
        excelDF = initialDF
        flag = true
      } else {
        excelDF = excelDF.union(initialDF)
      }

    }

    return excelDF
  }

Any help is much appreciated.

**Comment by gregosaurus** [comment]
Hello @aprasa02 !

What are the value set for `--driver-memory`, `--executor-memory` and `--executor-cores` when submitting your Spark Job ?

How many partitions does your file contains ?

Usually 100mb are not a problem for Spark.

Best,

Gregory.

**Comment by aprasa02** [comment]
cluster mode execution with driver memory 5g , executor memory 50g executor cores 64 . The partition we are setting as 100.I feel the issue comes when we are doing the union of multiple dataframes resulting in memory issue. we were testing with 28 tabs , means union of 28 dfs and return it. Since there is no option to create df for all the sheets in one go in crealytics API , forcibly I had to use POI to get sheet names and then passing to crealytics api and then union it all.

**Comment by nightscape** [comment]
Can you try and serialize the Excel Dataframes to e.g. Parquet and see if you get the same issues when using those?
Putting multiple sheets in one Dataframe would in theory be possible, but all your sheets would need to have the same schema.

**Comment by davidw76** [comment]
I am getting an out of memory error with the [online retail dataset](http://archive.ics.uci.edu/ml/machine-learning-databases/00352/)

**Comment by nightscape** [comment]
It seems that Apache POI is not the most memory-efficient library out there, mostly due to the fact that it provides a mutable API where you can read stuff, modify some arbitrary cells and then write back to a file.
We could switch to something like https://github.com/monitorjbl/excel-streaming-reader which does only the reading part and therefore can stream the data.
I guess that would allow you to read almost arbitrarily-sized data.

**Comment by habelson** [comment]
@aprasa02  Not related, but FYI, in most Hadoop\Spark deployments, you should be able to use the s3a file system directly and shorten your code, just set the 'path' option to be the full s3 URI:

.option("path","s3a://<bucket-name>/<folders>/<filename>

**Comment by nightscape** [comment]
Hey @litzebauer,
I saw you created a fork and fixed this issue.
Is it working out? 
Do you want to create a PR?

**Comment by litzebauer** [comment]
Almost, there is a transitive dependency conflict that I haven't gotten a
chance to resolve yet.

**Comment by nightscape** [comment]
I just released `0.9.6` to the Sonatype Maven repo.
It features a [`maxRowsInMemory` option](https://github.com/crealytics/spark-excel/blob/master/README.md#create-a-dataframe-from-an-excel-file) which when used switches to a streaming implementation using https://github.com/monitorjbl/excel-streaming-reader
This library doesn't support all functionality of Apache POI that's why I didn't make it the default (yet).
When running in dev environment, I actually had to override the version of `jackson` because of conflicts with the Spark-packaged version. If you run into any problems which look like a `jackson` version mismatch let me know, then we need to shade the dependency.

**Comment by davidw76** [comment]
I am getting some build errors with 0.9.6...

> [error] 71 errors were encountered during merge
> java.lang.RuntimeException: deduplicate: different file contents found in the following:
> C:\Users\dwb\.ivy2\cache\com.crealytics\spark-excel_2.11\jars\spark-excel_2.11-0.9.6.jar:com/fasterxml/jackson/annotation/JsonAutoDetect$1.class
> C:\Users\dwb\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\bundles\jackson-annotations-2.8.0.jar:com/fasterxml/jackson/annotation/JsonAutoDetect$1.class

**Comment by davidw76** [comment]
so I fixed the above problem by modifying my assembly merge strategy

but then I ran in to the same problem as you when running unit tests.. I fixed that by adding this to build.sbt..

```
assemblyShadeRules in assembly := Seq(
      ShadeRule.rename("com.fasterxml.jackson.**" -> "shadeio.@1").inAll
    )
```
