### ISSUE TITLE
How can I speed up the process of creating an Excel file?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [crealytics/spark-excel#195]
In **Scala/Spark** application I have `DataFrame` which has `~5000` rows. I am trying to create an Excel file from this DataFrame. I noticed that creation takes a too long time. In my case, I see such results in `Mesos`:
![results](https://user-images.githubusercontent.com/8999232/72922536-6568f000-3d77-11ea-8786-e28dd9e4b5ec.PNG)

As you can see, it took 2 hours to create the Excel file. What can you suggest to speed up the process? Let me know if you want some more information, please.

**Scala** version: `2.11.8`
**spark-excel** version: `0.12.0`
**Spark** version: `2.3.3`

Here is some Spark configurations which I use:
```
spark.serializer = org.apache.spark.serializer.KryoSerializer
spark.kryoserializer.buffer.max.mb = 1024
spark.executor.memory = 2g
spark.sql.autoBroadcastJoinThreshold = -1
spark.sql.files.ignoreCorruptFiles = true
spark.driver.memory = 30g
spark.driver.maxResultSize = 20g
spark.executor.cores = 1
spark.cores.max = 48
spark.scheduler.mode = FAIR
```

My simple code which I use to create Excel file from DateFrame as in documentation:
```
df.coalesce(1).write
  .format("com.crealytics.spark.excel")
  .option("dataAddress", "'My Sheet'!A1:Z1000000")
  .option("useHeader", "true")
  .option("dateFormat", "yy-mmm-d")
  .option("timestampFormat", "mm-dd-yyyy hh:mm:ss")
  .mode("append")
  .save("/hdd/home/Nogerbek/data.xlsx")
```

**Comment by nightscape** [comment]
Wow, that is really long. The job that takes 2.2h has 2.4TB of input according to the screenshot.
How is df constructed? Can you try doing a .cache on it first and then .count the items in order to force evaluation before starting to write?

**Comment by NogerbekNurzhan** [comment]
@nightscape thank you for your quick reply!

I create DataFrame from the data of the files which has `.gz` extension. These files are stored in `Hadoop`.

Here is how I created DataFrame:
```
df = spark.read
  .option("delimiter", "|")
  .csv("/{" + "path_to_the_files" + "}/*.gz")
  .filter(
    col("col_1").isin(array.distinct:_*)
  )
```

As you can see nothing extraordinary. `df.cache.count()` statement returns `3997`. It took me 2 hours to complete this statement. You recommend using the `.cache` method before each writing process, right? I think, even if the writing process speeds up, the total running time of the program will remain the same.

**Comment by nightscape** [comment]
The `.cache.count` method helps you find out if time is actually spent writing or calculating the DataFrame. If that already takes 2 hours then the problem is not caused by spark-excel.

**Comment by NogerbekNurzhan** [comment]
Sorry for the late reply. Unfortunately, I was not able to answer you earlier.

I want to know if the speed of creating an Excel file will change when caching the DataFrame.

I tested the code below. As you can see I have not big DataFrame which in this example called `baseDF`. I plan to use this Dataframe several times throughout the program. For that's why I decided to used `.persist()` method for that DataFrame.

In Mesos I see such results:
![Снимок](https://user-images.githubusercontent.com/8999232/73248645-8305e180-41dd-11ea-92c7-2de86ac272cc.PNG)

The first action which depends on the main DataFrame is executed in the first loop. For that's why the processes take a long time to complete in the first loop. Interesting things happen in the second loop. The counting process in the second loop was completed faster than in the first loop but it took 6.7 minutes to create the Excel file in the second loop. As you can see for this test in both two loops I filter the main DataFrame with the same identifiers. I excepted that in the second loop creating the Excel file world works faster than in the first loop.

After this test, I can conclude that caching slightly improves the performance of creating an Excel file. In your opinion, what any other methods can be used to speed up the process of creating an Excel file?

```
import org.apache.spark.sql.DataFrame

// Create the base DataFrame with all information.
var baseDF: DataFrame = spark.read.option("delimiter", "|").csv("/path_to_the_files/")

// Cache the base DataFrame.
baseDF.persist(StorageLevel.MEMORY_AND_DISK)

// Create arrays with the same identifiers
var array1 = Array("6fefc487-bd57-4fa2-808a-3845703b83d0", "9baba76b-07c2-48ec-a153-6cfb8b138ecf")
var array2 = Array("6fefc487-bd57-4fa2-808a-3845703b83d0", "9baba76b-07c2-48ec-a153-6cfb8b138ecf")
var storage = Array(array1, array2)

// Check if base DataFrame is empty or not.
if (!baseDF.head(1).isEmpty) {

    // Parse the array one by one.
    for (item <- storage) {

        // Filter the base DataFrame with specific identifiers.
        val df = baseDF.filter(col("col1").isin(item:_*))

        // Show the number of elements in filtered DataFrame.
        println(df.count())

        // Create the Excel file.
        df.coalesce(1)
          .write
          .format("com.crealytics.spark.excel")
          .option("dataAddress", "'Sheet 1'!A1:Z1000000")
          .option("useHeader", "true")
          .option("dateFormat", "yy-mmm-d")
          .option("timestampFormat", "mm-dd-yyyy hh:mm:ss")
          .mode("append")
          .save("/path_to_the_excel_file/" + filename)
    }
}
```

**Comment by long1208** [comment]
hi ,i get the same problem ，did you slove this problem

**Comment by long1208** [comment]
@nightscape

**Comment by nightscape** [comment]
No idea unfortunately... One would need to profile the execution of such runs, e.g. with VisualVM.
