### ISSUE TITLE
UnsupportedOperationException("empty.reduceLeft") when reading empty files

### ISSUE THREAD

**Issue by dzlab** [crealytics/spark-excel#203]
Cannot read empty Excel files, it's crashing my spark job with `empty.reduceLeft` exception

## Expected Behavior
Create an empty dataframe when the Excel file we are trying to read is empty

## Current Behavior
A scala exception is raise `UnsupportedOperationException("empty.reduceLeft")`

## Possible Solution
The problem is cause by using `reduce` here [ExcelRelation.scala#L115](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L115) instead we should use `reduceOption`. An possible solution would be:
```scala
excerpt.map(_.size).reduceOption(math.max) match {
  case None => Array()
  case Some(maxCellsPerRow) => {
    (0 until maxCellsPerRow).map(_ => StringType: DataType).toArray
  }
}
```

## Steps to Reproduce (for bugs)
Try read an empty excel file with following snippet with `hasHeader=true`
```scala
def read(filePath: String, hasHeader: Boolean)
      sqlContext.read.format("com.crealytics.spark.excel").options(
        Map(
          "useHeader" -> (if (hasHeader) "true" else "false"),
          "treatEmptyValuesAsNulls" -> "false",
          "inferSchema" -> "false"
        )
      ).load(filePath)
}
```

**Comment by nightscape** [comment]
Hey @dzlab, nice bug report! :smiley:
Would you mind opening a PR with your proposed changes?
Bonus points for adding a line to the `CHANGELOG.md` :wink:

**Comment by dzlab** [comment]
@nightscape I created a PR https://github.com/crealytics/spark-excel/pull/205
