### ISSUE TITLE
Writing a DataFrame to an Excel file doesn't produce Operation in Spark Logical Plan

### ISSUE THREAD

**Issue by cerveada** [crealytics/spark-excel#209]
Hello, I'm trying to add support for spark-excel in our Data Lineage Tracking tool [Spline](https://github.com/AbsaOSS/spline).

We use Spark `QueryExecutionListener` to capture the logical plan, and then we create lineage from it. Unfortunately there is no operation in the plan for writing in the Excel. On the other hand the Reading from Excel *is* contained in the plan.

We will be adding support for reading operation, but if you manage to make spark include the write operation in plan we can add support for that in Spline as well.

```
// This is the code I use when trying to produce the plan:

  val df = spark.read
    .format("com.crealytics.spark.excel")
    .option("useHeader", "true") // Required
    .load("/Users/abac720/test.xlsx")

  val res = df.select($"number" + 1, $"text")

  res.write
    .format("com.crealytics.spark.excel")
    .option("dataAddress", "'My Sheet'!B3:C35")
    .option("useHeader", "true")
    .save("data/output/batchWithDependencies/result.xlsx")
```

**Comment by nightscape** [comment]
@cerveada nice!
Could you try building this branch/PR locally and see if that changes anything?
https://github.com/crealytics/spark-excel/pull/210
In that branch I switched from a `Relation` to a `FileFormat` which is the way the CSV plugin also works.

**Comment by cerveada** [comment]
Yes, that seems to produce `SaveIntoDataSourceCommand`. So it would work for both: read and write. I produced the linage using this:
```
  import com.crealytics.spark.excel.ExcelDataFrameReader
  import com.crealytics.spark.excel.ExcelDataFrameWriter

  val df = spark.read.excel().load("/Users/abac720/test.xlsx")
  val res = df.select($"number" + 1, $"text")
  res.write.excel().save("data/output/batchWithDependencies/result.xlsx")
```
Hope that is a proper way how to call the library.

So if I understand it correctly, the old way (of read/write) will not be supported anymore, is that right? When do you planing to release this feature?

**Comment by nightscape** [comment]
There's still some test failures which need to get fixed.
Unfortunately, I don't have much time to spend on this at the moment, so a realistic time-frame would be within the next 1-2 months...

**Comment by cerveada** [comment]
Ok, I will add support for the reading only now and after the new version is released we can add support for it as well.

**Comment by cerveada** [comment]
At the end I was able to extract lineage data for both Read and Write. 

I don't know why it didn't work from the start, but Ii does now. So I'm closing this ticket.
