### ISSUE TITLE
Rename "useHeader" to "header"

### ISSUE THREAD

**Issue by EnverOsmanov** [crealytics/spark-excel#211]
What do you think if spark-excel will use "header" key parameter to read file with headers, the same as Spark does?

**Comment by nightscape** [comment]
I was thinking about that, too.
Would you mind opening a PR that includes the corresponding code and documentation changes?

**Comment by EnverOsmanov** [comment]
Yes, absolutely. I already changed corresponding code locally, and it worked fine. I will provide a PR on weekends.
