### ISSUE TITLE
ExcelRelation read file in driver

### ISSUE THREAD

**Issue by 3Dragan** [crealytics/spark-excel#22]
Hi,
Basically buildScan method will be run on driver, not executor.
It will process file and then send it's content through parallelize(), which is also bad practice for large stuff.

Options:
1)  use sc.hadoopFile(...) with custom ExcelInputFormat.
problems can be with providing parameters cause it use reflection to create instance of InputFormat

2) use sc.parallelize(..).flatMap( // read file, get List[Row])
It will read file on executor. Unfortunately, one executor.

**Comment by nightscape** [comment]
Hi @3Dragan,

up to now, we haven't used this plugin in large scale. More for one-of analysis of rather standard-sized Excel files.
Unfortunately I haven't worked with the `ExcelInputFormat` API and I also don't quite understand `2.`. Would the argument to `sc.parallelize` be the filename?

We're open to PRs :smiley:

**Comment by 3Dragan** [comment]
Hi, 
1. By "ExcelInputFormat" I mean implementation of InputFormat,
which will be run from https://spark.apache.org/docs/2.0.2/api/java/org/apache/spark/SparkContext.html#hadoopFile(java.lang.String,%20java.lang.Class,%20java.lang.Class,%20java.lang.Class,%20int)

The same approach is used for example in databricks csv Relation:
https://github.com/databricks/spark-csv/blob/master/src/main/scala/com/databricks/spark/csv/util/TextFile.scala

2. Yes. I have made a pull request with this one.

**Comment by nightscape** [comment]
Moved discussion to [corresponding PR](https://github.com/crealytics/spark-excel/pull/25).
