### ISSUE TITLE
Read Excel XML

### ISSUE THREAD

**Issue by daviddelucca** [crealytics/spark-excel#222]
Hello folks!

Is there any way of read Excel XML using this lib?

**Comment by nightscape** [comment]
Not that I'm aware of... Depends on what [`WorkbookFactory.create`](https://github.com/crealytics/spark-excel/blob/7edf4c3ecf7f2bd11023e7d1812a144fcc17f275/src/main/scala/com/crealytics/spark/excel/WorkbookReader.scala#L50) supports as input stream.

**Comment by quanghgx** [comment]
Hi @daviddelucca and @nightscape 
I think, not much we can do about this topic. Going to close this ticket and feel free to reopen it.
