### ISSUE TITLE
GC Overhead issue reading big excel file of size 50mb .

### ISSUE THREAD

**Issue by karamveer-scala** [crealytics/spark-excel#227]
I am facing issue reading an excel file of size 25 mb by crealytics library. I am using simple spark job to read excel but i get GC Overhead error issue .
I referred code from your git repository-
https://github.com/crealytics/spark-excel

   val df =spark.read
                             .format("com.crealytics.spark.excel")
			     .option("header", "true")
			     .option("sheetName", "sheet1")
                             .option("dataAddress", "sheet1")
			     .option("treatEmptyValuesAsNulls", "true") // Optional, default: true
			     .option("inferSchema", "true") // Optional, default: false
			     .option("addColorColumns", "false") // Optional, default: false
			     .option("maxRowsInMemory", 1000)
			     .option("timestampFormat", "MM-dd-yyyy HH:mm:ss") 
			     .load(path)
[sampleExcel.zip](https://github.com/crealytics/spark-excel/files/4409839/sampleExcel.zip)

## Current Behavior
> (RemoteBlock-temp-file-clean-thread) java.lang.OutOfMemoryError: GC overhead limit exceeded

## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version and language (Scala, Java, Python, R, ...): spark 2.4.5  scala: 2.11.6
* Spark-Excel version: 13.0.0
* Operating System and version, cluster environment, ...: linux Ubuntu 18.04.3 LTS

**Comment by karamveer-scala** [comment]
@nightscape  Kindly help .

**Comment by EnverOsmanov** [comment]
I run from Intellij 23.8 MB xlsx file (originally 75 MB csv) and it worked fine. Duration 5 min. No problem there.
Then I run from sbt 44.6 MB xlsx file (originally 513 MB csv) and it worked for 30 minutes and I cancelled it. But I didn't see any GC issues in VisualVM. 

JVM: OpenJDK 64-Bit Server VM (25.242-b08, mixed mode)
Java: version 1.8.0_242, vendor Private Build
environment variable: SBT_OPTS "-Xss2M -Xmx3G"
Source code: https://github.com/EnverOsmanov/sbt-assembly_TEST/tree/karamveer

**Comment by karamveer-scala** [comment]
@EnverOsmanov Thank you so much for your reply . I have 8 GB RAM in my system where i am running this scala program from sbt . my file size is of 25 mb .
If i run from sbt  like  "sbt -mem 5000 run" then in 2 or 3 minute of time i am able to see result dataframe and no GC error.
But my file size may have size of 100 mb then i can not wait for long time. 
Please suggest  the best approch to read a huge excel file .

**Comment by EnverOsmanov** [comment]
To process file faster, you should increase "maxRowsInMemory". But too big value could cause OutOfMemoryError. You need to find an optimal value suitable for your memory and desired time of processing. Increase as much as you can until it fails.

**Comment by karamveer-scala** [comment]
@EnverOsmanov  thank you ..

**Comment by karamveer-scala** [comment]
@EnverOsmanov  if i am reading big file . dont i required partioning ?

**Comment by EnverOsmanov** [comment]
You have 1 file. I don't think partitioning will help to read from 1 file. Maybe you can repartition afterwords for your next actions.

**Comment by EnverOsmanov** [comment]
@karamveer-scala After a detailed investigation, there was an issue found when reading big files. It was resolved in **0.13.5** version of spark-excel.
