### ISSUE TITLE
Can you support reading directories？

### ISSUE THREAD

**Issue by lingya** [crealytics/spark-excel#230]
eg  :
load("D:\data\excel\new\ ")   ?

**Comment by nightscape** [comment]
I've got an almost finished huge PR which allows just that:
https://github.com/crealytics/spark-excel/pull/210
Unfortunately I don't have much time to work on this at the moment...

**Comment by lingya** [comment]
thx!  let me try this PR.

**Comment by abhinavdangi** [comment]
By when can we expect this PR to be merged @nightscape?

**Comment by nightscape** [comment]
No idea to be honest. I'm currently not using spark-excel myself, so the quickest way to get this merged is if someone picks up the PR and gets the failing tests fixed.

**Comment by quanghgx** [comment]
Hi @lingya 
Follow up with Martin, #210 is ready after some revision in #389. From spark-excel 0.14.0 (and up), it natively supports this feature. There is an [example](https://github.com/crealytics/spark-excel/wiki/Examples:-Load-Multiple-Files) in wiki as well.
Feel free to reopen this ticket in case of further issues.
