### ISSUE TITLE
Writing a dataframe to .xls format and opening it shows a warning. 

### ISSUE THREAD

**Issue by anishsatalkar** [crealytics/spark-excel#256]
## Expected Behavior
Writing a dataframe using .xls as the extension for the file path should write using the xls format itself.
`df.write.format("com.crealytics.spark.excel").options(**options).save("file:///C:\\Users\\as21616\\some_file.xls")`

## Current Behavior
The instruction works fine. But when I open some_file.xls, Excel shows an error stating :
![image](https://user-images.githubusercontent.com/20540458/82875459-0a2d5100-9f55-11ea-93f5-f33e7a460a5b.png)
This suggests that the file format is not .xls as I wanted. 

## Question
Does spark-excel write files using .xlsx format itself, no matter what format I provide in the file path?

## My Environment
spark-excel : spark-excel_2.11-0.11.1.jar
OS : Windows 10
Spark version : 2.4.4

**Comment by nightscape** [comment]
Yes, quite definitely. Writing `.xls` files would require using different classes for writing which would make the entire code-base more complex.
If you really need `.xls` files I would try to find some tool that does the conversion.
