### ISSUE TITLE
java.lang.ClassNotFoundException: Failed to find data source: com.crealytics.spark.excel. Please find packages at http://spark.apache.org/third-party-projects.html

### ISSUE THREAD

**Issue by khaulaAhmad** [crealytics/spark-excel#273]
@nightscape 
Hey, 
I am finding an issue of ClassNotFoundException
my code is;
val context1 = new org.apache.spark.sql.SQLContext(sc)
val mydataframe = context1.read.format("com.crealytics.spark.excel")
//.option("location","c:/users/khaula ahmad/downloads/abc.xlsx")
.option("inferSchema", "true")
.option("useHeader", "true")
.option("treatEmptyValuesAsNulls", "true")
.option("addColorColumns", "False")
.load("c:/users/khaula ahmad/downloads/abc.xlsx”)

I am using spark-excel_2.12-0.13.1.jar and it's compatible poi's.
spark-shell --jars poi-4.1.0.jar, poi-ooxml-4.1.0.jar, poi-ooxml-schemas-4.1.0.jar, spark-excel_2.12-0.13.1.jar
Let me know how to resolve the issue

**Comment by nightscape** [comment]
You should specify the dependencies as stated in the README:
```
spark-shell --packages com.crealytics:spark-excel_2.12:0.13.1
```

**Comment by SanjirSalsabil** [comment]
Hello, 
May I know what's java.langIllegalArgumentException: Parameter &#34;useHeader&#34; is missing in options.

To read xlsx file my code is following 
df_excel= spark.read.format("com.crealytics.spark.excel").option("header", "true").option("treatEmptyValuesAsNulls", "false").option("inferSchema", "false").option("addColorColumns", "false").load("/FileStore/tables/test.xlsx")

display(df_excel)


Using Apache Spark 2.4.5, Scala 2.11
spark-excel 2.11:0.12.5


Full error: 


java.lang.IllegalArgumentException: Parameter &#34;useHeader&#34; is missing in options.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling o355.load.
: java.lang.IllegalArgumentException: Parameter "useHeader" is missing in options.
	at com.crealytics.spark.excel.DefaultSource.checkParameter(DefaultSource.scala:68)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:31)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:351)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:311)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

IllegalArgumentException                  Traceback (most recent call last)
<command-3453852649324202> in <module>
----> 1 df_excel= spark.read.format("com.crealytics.spark.excel").option("treatEmptyValuesAsNulls", "false").option("inferSchema", "false").option("addColorColumns", "false").load("/FileStore/tables/test.xlsx")
      2 
      3 display(df_excel)

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     77                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
     78             if s.startswith('java.lang.IllegalArgumentException: '):
---> 79                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
     80             raise
     81     return deco

IllegalArgumentException: 'Parameter "useHeader" is missing in options.'

**Comment by nightscape** [comment]
Please try with the newest version.

**Comment by SanjirSalsabil** [comment]
Thanks, it works for a single Excel file. 
However, for the list of sheets, it didn't work. Do you have any idea how to read several .xlsx files in a spark data frame!

**Comment by nightscape** [comment]
In Scala it would be something like this (untested):
```scala
List("file1.xlsx", "file2.xlsx", "...").map { f =>
  spark.read.format("com.crealytics.spark.excel").option("header", "true").option("treatEmptyValuesAsNulls", "false").option("inferSchema", "false").option("addColorColumns", "false").load(f)
}.reduce(_ union _)
```
