### ISSUE TITLE
DF's behaviour is unexpected when using of excel's stream reading

### ISSUE THREAD

**Issue by vasilnikolay** [crealytics/spark-excel#278]
Hi!

## Current Behavior
I am trying to laod .xlsx file into dataframe. The size of the file is about 40Mb.
Putting data to DF goes fine but when I invoke any method on df it give me no result for a long time(more than an hour) and I cancel a job.

## Steps to Reproduce (for bugs)
    the first step looks like this and works succesfully
    ```
    val sparkDF = spark.read.format("com.crealytics.spark.excel")
                .option("header", true)
                .option("inferSchema", "true")
                 .option("excerptSize", 100)
               .option("maxRowsInMemory", 2)
                .option("sheetName", "OSA")
                .load("/mnt/databricks/TEST/KPI_list_082020.xlsx")
    ```
The next step is counting rows: sparkDF.count(),show().
Regardless of maxRowsInMemory parameter -  1 and up to 20, it works the same - I have no results for  hours.

## Your Environment
 I am using Databricks cluster with the following configuration
( Apache Spark 2.4.5, Scala 2.11)
Worker Type 14.0 GB Memory, 4 Cores, 0.75 DBU
Driver Type 14.0 GB Memory, 4 Cores, 0.75 DBU

File is placed in Azure Blob Storage.

**Comment by nightscape** [comment]
Can you check if it makes a difference if you copy the file to your local disk or call `.cache` on the DataFrame before running any further operations?

**Comment by vasilnikolay** [comment]
Both cases don't give a result.
![Screenshot from 2020-08-06 17-03-22](https://user-images.githubusercontent.com/29737513/89541246-ce412280-d806-11ea-9d01-2e701b7b8416.png)
DF is created as expected, then I start to wait long again.

Copying file to cluster's local filesystem give the same result

**Comment by EnverOsmanov** [comment]
20 rows are almost nothing for such a huge excel file. Could you try to put more rows in memory? 10000?

**Comment by vasilnikolay** [comment]
I found your benchmark in the mentioned issue for file with similar size (44 Mb). In your case it took ~30 minutes. Invoking .cache() on the dataframe works longer and I leave the running without a result. 

Also I was trying to put 1000, 10 000 and even 100 000 rows to memory -  everything is the same.

Could it be that these values are not suitable for the given cluster configuration?

**Comment by EnverOsmanov** [comment]
@vasilnikolay , in my case it didn't take ~30 minutes, I canceled it.
Don't set big numbers for "maxRowsInMemory", I confused it with a buffer.

The fix for this issue is coming very soon.

**Comment by EnverOsmanov** [comment]
It should be resolved in **0.13.5** version of spark-excel. If not, feel free to reopen.

**Comment by vasilnikolay** [comment]
@EnverOsmanov , thanks.
I see you ahve just merged some changes into master branch. Right?
So could I use the master to test changes applied to my task?

**Comment by EnverOsmanov** [comment]
@vasilnikolay , right.
Yes, you can. But it is much easier to use 0.13.5. It is available since my last comment.

**Comment by vasilnikolay** [comment]
@EnverOsmanov , It works for 20 seconds for 40Mb(~600k rows).
Thanks a lot!
