### ISSUE TITLE
Empty rows are automatically removed. Is it possible to not have that behavior?

### ISSUE THREAD

**Issue by Bryce21** [crealytics/spark-excel#285]
## Expected Behavior
I'm using an excel sheet that contains empty rows. When I read that into a dataframe it is losing the empty rows. My data is very delicate and needs those empty rows for downstream processes.

## Current Behavior
I'm losing the empty rows.

## Steps to Reproduce (for bugs)
[example_data.xlsx](https://github.com/crealytics/spark-excel/files/5152348/example_data.xlsx)
Load the attached file data. This is not the real data I'm using but illustrates the problem. Using this code:

    val columns =
      (1 to numberOfColumnsToParse).map(n => StructField(s"$n", StringType))
    val df = spark.read
      .format("com.crealytics.spark.excel")
      .option("dataAddress", s"$da")
      .option("useHeader", header)
      .option("treatEmptyValuesAsNulls", "true")
      .option("inferSchema", "false")
      .option("addColorColumns", "false")
      .option("ignoreLeadingWhiteSpace", "true")
      .option("ignoreTrailingWhiteSpace", "true")
      // .option("maxRowsInMemory", 20)
      .schema(StructType(columns))
      .load(FileUtils.normalizeFilePath(path))

This is result:
![image](https://user-images.githubusercontent.com/24858593/91761609-1a337d00-eba3-11ea-864c-bb5ec4f83fa1.png)

There should be empty rows above metadata. In the actual data there are around 45 such occurrences and it's throwing the dataframe off.

## Your Environment
"com.crealytics" %% "spark-excel" % "0.12.0"
val sparkVersion = "2.4.4"
val hadoopVersion = "3.1.2"

This might just be a spark issue because when a csv file is handled the rdd had to be parsed and add an empty row in like so: 
      .readFileAsStringRDD(path)
      .toDS()
      .map(rowString => if (rowString.isEmpty) "$$$emptyRow" else rowString)

I'll admit that I'm new to both spark and scala so it's possible there is an obvious solution that I'm not seeing and this is a dumb question. I'm also willing to add more information as requested. Any help is appreciated!

**Comment by nightscape** [comment]
This probably wont solve your problem, but could you first try upgrading to the latest version `0.13.1`?

**Comment by Bryce21** [comment]
I downgraded to get around this issue: https://github.com/crealytics/spark-excel/issues/122. I ended up using POI and parsing the file directly if anyone is interested. Which also didn't handle empty rows, columns, and cells well interesting enough. Should I close this?

**Comment by nightscape** [comment]
If spark-excel behaves the same way as POI then you'd need to report any bugs to POI.
If it's different and looks like a bug then you can leave the issue open.
Unfortunately, I don't have any time to work on spark-excel at the moment, so don't expect this to get fixed.
But feel free to open PRs once you've familiarized yourself sufficiently with Spark, Scala and spark-excel.

**Comment by quanghgx** [comment]
Hi @Bryce21 
Thanks for your clear and detailed issue description. @nightscape is right, it's the same with Apache POI.
With your suggestion, spark-excel v0.14.0 (and up) has an option for that, [Example: Keeping Undefined Rows](https://github.com/crealytics/spark-excel/wiki/Examples:-With-Row-Number-&-Undefined-Rows#keeping-undefined-rows). Please take a look when you have time.
Sincerely,

**Comment by quanghgx** [comment]
Going to resolve this ticket. Feel free to reopen it in case of further issues.
