### ISSUE TITLE
Any option to format excel columns like font, color fill etc..

### ISSUE THREAD

**Issue by naveenag86** [crealytics/spark-excel#289]
Iam looking at formatting excel worksheet formatting..

first columns with font size 18, bold and fill color - yellow..

Any possibilities?

**Comment by nightscape** [comment]
spark-excel supports reading color, but not writing it.
We're open to PRs though 😉

**Comment by quanghgx** [comment]
Hi @naveenag86 ,
Going to close this ticket. Hope we can re-open this one day.
Sincerely,
