### ISSUE TITLE
Any option to read in a file like or byte object?

### ISSUE THREAD

**Issue by gstathisfs** [crealytics/spark-excel#290]
I am trying to read in an xlsx document that is pulled off an email in python on Databricks but it seems like spark excel only accepts a file path when calling .load(). 

I have tried just passing in the byte string representation of the payload and also tried using the io module to create a file like object from the byte string but this also does not seem to work.

Just wanted to know if there is there any option to do this? or plans to add it?

**Comment by nightscape** [comment]
It is currently not supported, but the WorkbookReaders in principle operate on Java InputStreams:
```scala
class DefaultWorkbookReader(inputStreamProvider: => InputStream, workbookPassword: Option[String])
```
If you want to submit a corresponding PR, we're open 😃 
Am additional question is if Python can construct InputStreams at all...

**Comment by quanghgx** [comment]
Hi @gstathisfs 
From my understanding, spark-excel doesn't have plans to support this in near future. Spark-excel can be used with other languages that spark support (python, R)
 
Going to close this ticket, however, feel free to re-open it or a PR will be great.
Sincerely,
