### ISSUE TITLE
Maturity / Production Readiness

### ISSUE THREAD

**Issue by mvervuurt** [crealytics/spark-excel#3]
Hi Martin,

I am enthusiastic about your library ☺︎

May I ask your opinion about the production readiness or maturity of your library? Would you recommend using it in production?

Danke, Mark

**Comment by nightscape** [comment]
Hi Mark,

there's surely some bugs lurking in the code :wink: 
I've been using it myself a few times and fixed the bugs I stumbled upon.

I would say just try it and report any bugs here, or even better: create a PR with the fix :smile:

Best
  Martin

**Comment by mvervuurt** [comment]
Hi Martin,

Thanks for your straight answer ;)

Best,
Mark
