### ISSUE TITLE
Scala 2.13

### ISSUE THREAD

**Issue by ASchmidt84** [crealytics/spark-excel#301]
Hi,

only want to ask for support Scala 2.13 ? Is that already planned? When do you think it will be available?

Thank you

**Comment by EnverOsmanov** [comment]
Not until Spark will support it. It is [not](https://mvnrepository.com/artifact/org.apache.spark/spark-core) for now.
You can follow the status of Spark for Scala 2.13 [here](https://issues.apache.org/jira/browse/SPARK-25075).
