### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: Failed to find data source: com.crealytics.spark.excel.

### ISSUE THREAD

**Issue by hennar** [crealytics/spark-excel#32]
Overnight I can't seem to find the package anymore? Is it being updated?

**Comment by nightscape** [comment]
Nope, no changes or deployments yesterday.
Were you running `spark-shell`, `spark-submit` or something completely different?
Can you give more details how you launched your Spark application?

**Comment by nightscape** [comment]
Hey @hennar, did you manage to fix the problem?
