### ISSUE TITLE
Read me has outdated "sheetName" property

### ISSUE THREAD

**Issue by JakeDelmas** [crealytics/spark-excel#320]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.
Moreover, please read the [`CHANGELOG.md`](../../blob/master/CHANGELOG.md) file for any changes you might have missed.

## Expected Behavior
> Read me contains examples using up to date code for current version

## Current Behavior
> Read me has outdated "sheetName" property
```
val df = spark.read
    .format("com.crealytics.spark.excel")
    .option("sheetName", "Info")
    .option("header", "true")
    .schema(peopleSchema)
    .load("People.xlsx")
```

## Possible Solution
> Update examples in Read Me

```
val df = spark.read
    .format("com.crealytics.spark.excel")
    .option("dataAddress", "'Info'!A1")
    .option("header", "true")
    .schema(peopleSchema)
    .load("People.xlsx")
```

## Steps to Reproduce (for bugs)
> Provide a link to a live example, or an unambiguous set of steps to
> reproduce this bug. Include code to reproduce, if relevant.
> Example:
1. Download the example file uploaded [here](http://example.com/)
2. Start Spark from command line as `spark-shell --packages com.crealytics:spark-excel_2.12:x.y.z --foo=bar`
3. Read the downloaded example file
    ```
    val df = spark.read
    .format("com.crealytics.spark.excel")
    .option("dataAddress", "'My Sheet'!B3:C35")
    .load("example_file_exhibiting_bug.xlsx")
    ```

## Context
> Trying to read 1 sheet in a excel file that contains multiple sheets

## Your Environment
> Include as many relevant details about the environment you experienced the bug in
* Spark version and language (Scala, Java, Python, R, ...):
* Spark-Excel version:
* Operating System and version, cluster environment, ...:

**Comment by nightscape** [comment]
Hi @JakeDelmas, thanks for the report!
In such simple cases you can just go ahead and open a PR :wink: 
Would you mind creating one?
Thank you!

**Comment by quanghgx** [comment]
Hi @nightscape and @JakeDelmas 
I've just prepared a PR for this in https://github.com/crealytics/spark-excel/pull/410. Please help review it.

**Comment by quanghgx** [comment]
Fixed, thanks @JakeDelmas and Martin.
