### ISSUE TITLE
Issue with reading a long number > 11 digit

### ISSUE THREAD

**Issue by waiyan1612** [crealytics/spark-excel#321]
## Expected Behavior
I have a simple xlsx file with a column that can have numbers more than 11 digits.
```
+------------+
|id          |
+------------+
|12345678901 |
|123456789012|
|123456789-0 |
+------------+
```
I want to create a DataFrame with id as a `StringType` and read all the values as they are (i.e. Not converted to a scientific notation etc)

## Current Behavior
I have tried the following options.
1. custom schema with `id`=`StringType`
2. `inferSchema=True`
3. `inferSchema=False`
4. default options.

Every option gives me the same output.
```
+-----------+
|id         |
+-----------+
|12345678901|
|1.23457E+11|
|123456789-0|
+-----------+

root
 |-- id: string (nullable = true)
```
The issue lies in the second row. I am unable to get `123456789012`. Parsing `1.23457E+11` to `Long` does not help because I have already lost the precision. 

I also noticed that this issue does not occur if this column is [formatted](https://docs.microsoft.com/en-us/office/troubleshoot/excel/long-numbers-incorrectly-in-excel) as `Text` instead of `General` in Excel. Unfortunately, I do not have control over this.

## Steps to Reproduce (for bugs)
1. Download the attached excel file.
[long_number.xlsx](https://github.com/crealytics/spark-excel/files/5601631/long_number.xlsx)

2. Read the downloaded example file
    ```scala
    val spark: SparkSession = SparkSession.builder()
      .appName("test-excel")
      .master("local[*]")
      .getOrCreate()

    val path = "long_number.xlsx"
    val columns = spark.read.format("com.crealytics.spark.excel")
      .option("header", true)
      .load(path).columns
    val allStringSchema = StructType(columns.map(x => StructField(x, StringType, true)))
    println(allStringSchema)

    println("Using customSchema", allStringSchema)
    val df = spark.read.format("com.crealytics.spark.excel")
      .option("header", true)
      .schema(allStringSchema)
      .load(path)
    df.show(false)
    df.printSchema()

    println("Using inferSchema=true")
    val df2 = spark.read.format("com.crealytics.spark.excel")
      .option("header", true)
      .option("inferSchema", true)
      .load(path)
    df2.show(false)
    df2.printSchema()

    println("Using inferSchema=false")
    val df3 = spark.read.format("com.crealytics.spark.excel")
      .option("header", true)
      .option("inferSchema", false)
      .load(path)
    df3.show(false)
    df3.printSchema()

    println("Using defaults")
    val df4 = spark.read.format("com.crealytics.spark.excel")
      .option("header", true)
      .load(path)
    df4.show(false)
    df4.printSchema()
    ```

## Context
I have a column in my excel sheet that is used as an identifier. I need to get the values as they are but some rows are being converted to a scientific notation and it's irreversible.

## Your Environment
* Scala 2.12, Spark 2.4.4
* Spark-Excel version: 0.13.5

**Comment by nightscape** [comment]
Hi @waiyan1612, thanks for the detailed report.
Do you know how to locally debug the code?
If so, could you create a breakpoint [here](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/DataColumn.scala#L84) and check what the values of `value` and `field` are?

**Comment by nightscape** [comment]
I just added Gitpod, so you can try without having to setup anything locally:
https://gitpod.io/#https://github.com/crealytics/spark-excel

**Comment by waiyan1612** [comment]
Terribly sorry for the delayed response.

> If so, could you create a breakpoint [here](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/DataColumn.scala#L84) and check what the values of `value` and `field` are?

Here's what I see for the first row (non-problematic record).
- `field` - `StructField("id", StringType, true)`
- `value` - `Some("12345678901")`

And what I see for the second row (problematic record).
- `field` - `StructField("id", StringType, true)`
- `value` - `Some("1.23457E+11")`

**Comment by nightscape** [comment]
Ok. So if `field` is a `StringType` then it must have used `stringValue` calculated [here](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/DataColumn.scala#L33-L43).
Could you step through the `cell.getCellType match { ...` part in L33-L43 and check which case matches?
I'm guessing it's line 43 and the `dataFormatter.formatCellValue(cell)` is producing the scientific notation.
If so, could you check what other methods on `cell` could be used to produce the desired value?

**Comment by waiyan1612** [comment]
I ended up tracing line 43 (dataFormatter.formatCellValue(cell)`  all the way back to POI. 

Because the cell format is `General`, [POI formatted it](https://github.com/apache/poi/blob/REL_4_1_2/src/java/org/apache/poi/ss/usermodel/DataFormatter.java#L868-L874) the same way that it is displayed in Excel.

>        Format numberFormat = getFormat(cell, cfEvaluator);
>         double d = cell.getNumericCellValue();
>         if (numberFormat == null) {
>             return String.valueOf(d);
>         }
>         String formatted = numberFormat.format(Double.valueOf(d));
>         return formatted.replaceFirst("E(\\d)", "E+$1"); // to match Excel's E-notation

I am a bit reluctant to change the behaviour of `dataFormatter.formatCellValue(cell)` since it might impact other formats. I tried adding another `case` statement before we go to the default case (i.e. between lines 42 and 43)
```
case CellType.NUMERIC => Option(cell.getNumericCellValue).map(_.toString)
```
This gives me `1.23456789012E11` instead of `1.23457E+11`. Not ideal, but at least this can be converted back to double / long to string.

**Comment by nightscape** [comment]
Great detective work! :smile: :+1:
Is there maybe a way to specify a formatter that has a certain number of digits?

**Comment by waiyan1612** [comment]
`DataFormatter`'s docs say

>  DataFormatter contains methods for formatting the value stored in an Cell. This can be useful for reports and GUI presentations when you need to display data exactly as it appears in Excel. 

May be we can write a separate `DataFormatter` but the effort will be huge. I tried overwriting the `generalNumberFormat` of `DataFormatter` which is the culprit in this issue.

```
lazy val dataFormatter = new DataFormatter()
lazy val customGeneralFormatter = new CustomExcelGeneralNumberFormat(Locale.US)
dataFormatter.addFormat("General", customGeneralFormatter)
dataFormatter.addFormat("@", customGeneralFormatter)
```

1. First, create a new format `CustomExcelGeneralNumberFormat` similar to [POI's ExcelGeneralNumberFormat but with no restrictions on number of digits](https://github.com/apache/poi/blob/REL_4_1_2/src/java/org/apache/poi/ss/usermodel/ExcelGeneralNumberFormat.java#L72-L82). (Note: The locale should be retrieved from the workbook instead of being hardcoded to US.)
2. Then replace the `ExcelGeneralNumberFormat` with our new `CustomExcelGeneralNumberFormat` when the cell format is `General` or `@` - [ref1](https://github.com/apache/poi/blob/REL_4_1_2/src/java/org/apache/poi/ss/usermodel/DataFormatter.java#L370-L372), [ref2](https://github.com/apache/poi/blob/REL_4_1_2/src/java/org/apache/poi/ss/usermodel/DataFormatter.java#L435-L437). We do this by overwriting the `DataFormatter`'s `format` [hashmap](https://github.com/apache/poi/blob/REL_4_1_2/src/java/org/apache/poi/ss/usermodel/DataFormatter.java#L1075-L1077).

**Comment by nightscape** [comment]
Just had a short look, that approach sounds feasible. `ExcelGeneralNumberFormat` is not final, so one could inherit from it and only override the required method.
