### ISSUE TITLE
How to use parameter 'timestampFormat' when read

### ISSUE THREAD

**Issue by wenyangchou** [crealytics/spark-excel#324]
```
    val df = ss.read.format("com.crealytics.spark.excel")
      .option("header",value = true)
      .option("timestampFormat","MM-dd-yyyy")
      .load("/Users/zhouwenyang/Desktop/test.xlsx")
    df.show(10)
    ```
I wanted the time cell is formatted ,how the output is string that the time cell is not formatted

output data:
+----+---+-------------------+------------------+
|name|age|           birthday|      english_name|
+----+---+-------------------+------------------+
|zhou| 19|1993/10/24 12:00 AM|          quan dan|
| wen| 20|1993/10/24 12:00 AM|holilai jackque li|
|yang| 18|1993/10/24 12:00 AM|              aaaa|
+----+---+-------------------+------------------+

what is the problem and how can I format the birthday??

**Comment by wenyangchou** [comment]
If the issue has been solved, please target it .

**Comment by nightscape** [comment]
The `timestampFormat` is for parsing and writing to Excel files.
I assume the table you have pasted here is the result of a `df.show()` which prints timestamps in Spark's internal format which has nothing to do with `timestampFormat`.

**Comment by manish-jain-alept** [comment]
@nightscape Yes, that's which prints timestamps in Spark's internal format.
But spark.read.excel() returns DF. So, when read from that DF always return wrong Date with Format.
Ex. excel column having date with format **dd/MM/yyyy** and we want to validate the format in that column, how we get it. Because it always return date with **yyyy-MM-dd** format.
It would be really helpful, if you can direct us in some accurate direction.

**Comment by nightscape** [comment]
Internally, Excel saves timestamps as `long` values and stores the format with which dates should be displayed separately.
spark-excel only takes care of getting the data out as values of type date and does not care about the display format.
If you want to format the dates from the DF, you can check out this article:
https://medium.com/expedia-group-tech/deep-dive-into-apache-spark-datetime-functions-b66de737950a

**Comment by quanghgx** [comment]
Hi @manish-jain-alept 

Totally agree with @nightscape . This is about displaying date/timestamp value in spark. It is not specific to spark-excel.

Please take a try with:
```python
<your original code>

df.select(date_format('birthday', 'dd/MM/yyyy').alias('birthday_2')).show()
```
Spark Document for this API: https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.functions.date_format.html

I am going to resolve this ticket, however, feel free to reopen it.
Sincerely,
