### ISSUE TITLE
Nexus badge does not update anymore

### ISSUE THREAD

**Issue by nightscape** [crealytics/spark-excel#331]
## Expected Behavior
After pushing a new release to Maven Central, the badge at the top of the README should display the newest version.

## Current Behavior
The badge still shows a rather old version `0.13.3-9...SNAPSHOT`.

## Possible Solution
Research for possible problems with the badge and check if someone else has found a solution.

**Comment by quanghgx** [comment]
Resolved by @pjfanning in https://github.com/crealytics/spark-excel/pull/420
