### ISSUE TITLE
Error when excel file have cell with formular

### ISSUE THREAD

**Issue by cedtnee** [crealytics/spark-excel#35]
Hi, 
My stack:
-scala 2.10
-spark 1.6
-spark-excel_2.10 version : 0.8.3

My sheet have cell with formular , i have this error:
java.lang.RuntimeException: Unknown cell type 2 for NOW()+A2
  at com.crealytics.spark.excel.ExcelRelation$$anonfun$1$$anonfun$3.apply(ExcelRelation.scala:66)
To correct this issues , i get the latest version of source and change scala version to match with my stack  and update ExcelRelation.scala.

Please can you check my update and push a new spark-excel_2.10 version : 0.8.3  on maven central?

See attachment.
[ExcelRelation.zip](https://github.com/crealytics/spark-excel/files/1445982/ExcelRelation.zip)

Regard

**Comment by nightscape** [comment]
Hi @cedtnee,

several notes:

- I haven't tested with Spark < 2.0 in a while
- There is an [open issue](https://github.com/crealytics/spark-excel/issues/30) and a corresponding [pull request](https://github.com/crealytics/spark-excel/pull/31) for supporting formulas. Can you check if the PR solves your problem?
- If you want to contribute changes (which is a great thing to do), it's best if you fork the project and create a pull request. If you haven't done this before, Github itself has some good resources on the topic, e.g. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Best
  Martin
