### ISSUE TITLE
When some data lines in the middle are empty, you cannot see these empty data when outputting data

### ISSUE THREAD

**Issue by Yao-sss** [crealytics/spark-excel#352]
When some data lines in the middle are empty, you cannot see these empty data when outputting data.

<img width="292" alt="Snipaste_2021-02-25_18-00-28" src="https://user-images.githubusercontent.com/44462120/109137053-bfff2780-7793-11eb-9e00-3c81d96b4f02.png">

Null data is sometimes normal.

The following is the result of df.show()

![Snipaste_2021-02-25_18-07-24](https://user-images.githubusercontent.com/44462120/109137598-559ab700-7794-11eb-82b9-916884a0b699.png)

**Comment by nightscape** [comment]
Does it only occur when all cells are empty, or also when it's only a few?

**Comment by Yao-sss** [comment]
All cells are empty

**Comment by Yao-sss** [comment]
Setting dataAddress="A1" cannot read all the data, and when some cells are empty, only 4 columns of data can be read, and the empty columns will be merged
![Snipaste_2021-02-26_10-48-20](https://user-images.githubusercontent.com/44462120/109248654-28481a80-7821-11eb-84ca-f5db16704353.png)
![Snipaste_2021-02-26_10-48-34](https://user-images.githubusercontent.com/44462120/109248667-2da56500-7821-11eb-8fca-477d23a802f0.png)

The following is the excel data

<img width="533" alt="Snipaste_2021-02-26_10-57-17" src="https://user-images.githubusercontent.com/44462120/109248944-bd4b1380-7821-11eb-878e-4b022c4e1410.png">

**Comment by KanduriR** [comment]
A similar issue I have observed is when using dataAddress to start reading from a specific row. If a column in that row is empty then that entire column is omitted for reading. 

This is a sample data 
![image](https://user-images.githubusercontent.com/7806480/113097097-1acbe900-9242-11eb-9335-1271f35485c7.png)

And upon reading it in databricks this is the output I observed
![image](https://user-images.githubusercontent.com/7806480/113097172-3505c700-9242-11eb-90be-5d21a3199ae5.png)

Column A in the excel sheet is completely missed out. For the sample data case shown [in the above comment](https://github.com/crealytics/spark-excel/issues/352#issuecomment-786377085) if read from A2 then column D and E will not be read at all once a blank cell is hit. 

I'm hoping this is a bug fix and not a library limitation

**Comment by KanduriR** [comment]
@nightscape I've tried that too. My initial understanding was also that by specifying the schema that cells matching that particular column range will be read but they all came out as Null values.

**Comment by quanghgx** [comment]
Hi @Yao-sss and @KanduriR ,
Spark-excel version 0.14.0 (and up) supports this case well now, I think. Please take a try with:
```python
.option("keepUndefinedRows", True) 
```
This option also has a dedicated wiki page  [Keeping Undefined Rows](https://github.com/crealytics/spark-excel/wiki/Examples:-With-Row-Number-&-Undefined-Rows#keeping-undefined-rows)
Please help take a try again with spark-excel 0.14.0 (and up).
Sincerely,

**Comment by quanghgx** [comment]
Going to resolve this ticket, however, feel free to re-open it!
Sincerely,
