### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by dnskmr** [crealytics/spark-excel#355]
The actual value in the cell is 6/28/2020 but in the excel its displaying as 2020-06-28, but when we double click the cell it will show the value as 6/28/2020. When I read the excel using spark-excel jar its providing the display value not the actual value.

Note: In the excel custom format has been applied as yyyy-mm-dd. I would like to retrieve the actual value as 6/28/2020.

Any solution ?

**Comment by skybutter** [comment]
Can you provide your code that read the excel file?  What options did you specify?  Are you using inferSchema or specifying a schema?  Those information would help find a solution.  Plus, if you can attach sample of the excel file that would be good.

**Comment by quanghgx** [comment]
Hi @dnskmr 

Please help share a bit more detail for this issue when you have time.
Going to close this ticket. Feel free to reopen it.
