### ISSUE TITLE
Add option for pathGlobFilter and partitioning

### ISSUE THREAD

**Issue by bitsofinfo** [crealytics/spark-excel#365]
Most DataFrameReader formats in spark support. `pathGlobFilter` and on `load(<pathWIthPartitions>)` it will grab all of them and denote the partition names in the dataframe, would be great if this did too.

**Comment by nightscape** [comment]
You could check if https://github.com/crealytics/spark-excel/pull/210 accidentally does this already.

**Comment by bitsofinfo** [comment]
maybe partitioning will be covered? not sure

**Comment by nightscape** [comment]
#210 reuses more of the code from the Spark CSV reader, but I haven't tested what implications this has in terms of observable behavior.
It would be great if you could give that branch a try and post your findings here.

**Comment by quanghgx** [comment]
Hi @bitsofinfo 
Continue with #210, we got it merged. Please help take a try again with the latest version in the main branch.
There is also a simple example for this in wiki: https://github.com/crealytics/spark-excel/wiki/Examples:-Load-Multiple-Files
Sincerely,

**Comment by quanghgx** [comment]
Going to resolve this ticket. Feel free to reopen it in case of further issues.
