### ISSUE TITLE
empty column names blocks reading columns

### ISSUE THREAD

**Issue by datadu-de** [crealytics/spark-excel#366]
same problem as described in #122 
there is no way to make spark-excel read columns with an emtpy cell in the column header

## Expected Behavior
* if `dataAddress` is specified, all cols in the range should be read, even if the header cell is empty in some cols.
* cols with empty header rows should have automatic names like `_c0` etc. 
* many systems produce files like this
  * ![image](https://user-images.githubusercontent.com/49077745/114918303-3846a880-9e27-11eb-83d5-f691b5cd2317.png)
  * this should be possible/easy to read

## Current Behavior
* with latest version there is no way to read a column with empty header col, even if `dataAddress` explicitly covers the cell
* ![image](https://user-images.githubusercontent.com/49077745/114919741-e99a0e00-9e28-11eb-9ed5-2c38c4ede115.png)

## Possible Solution
unfortunately I'm not sure why this is not working, as it seemed to have been working in previous versions (<= v12 as discussed in #122 ) - and works with csv as well

## Steps to Reproduce (for bugs)
[df_empty_headers_not_working.xlsx](https://github.com/crealytics/spark-excel/files/6320379/df_empty_headers_not_working.xlsx)
```
df = spark.read.format("com.crealytics.spark.excel") \
.option("inferSchema", False) \
.option("header", True) \
.option("treatEmptyValuesAsNulls", False) \
.option("dataAddress", "0!A8:Q19") \
.load("df_empty_headers_not_working.xlsx")
```

## Context
we're having tons of excel-sources with the strangest formats produced by various formats. For efficient processing it would be enormously helpful to be able to handle such formats more gracefully.

## Your Environment
* Spark version 3.0.1, Python
* Spark-Excel version:com.crealytics:spark-excel_2.12:0.13.7
* Databricks RT 7.3 LTS on Azure

**Comment by nightscape** [comment]
Hi @datadu-de, thanks for the detailed report.
Are you proficient enough with Scala & Spark to try debugging this and creating a PR?
The problem is probably somewhere around here:
https://github.com/crealytics/spark-excel/blob/main/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L127-L156

**Comment by koiralo** [comment]
Hi @nightscape can I take this issue, I have used spark-excel for some time and this might be a good start to contribute a little bit,

**Comment by datadu-de** [comment]
@nightscape @koiralo 
Hi guys,
sorry, I think I'm not proficient enough... looked at the code but couldn't figure it out.
@koiralo It would be awesome if you could take this 👍 

would be awesome if you could also consider the case where there's **two** header rows (i.e. row 7 in the very first screenshot)

Very much appreciated

**Comment by nightscape** [comment]
Hey @koiralo great!!
If you need help just post here 👍

**Comment by koiralo** [comment]
Thanks, @nightscape 
Do you think the issue is here, https://github.com/crealytics/spark-excel/blob/main/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L127-L156
I checked it and the `headerNames` or `firstRow` is already without the empty values. 
Can you locate the part where it reads file for the first time and get headers row?

**Comment by nightscape** [comment]
Hmm, could you check the values of `rowInd` and `colInd` here?
https://github.com/crealytics/spark-excel/blob/5322342b65352bed2760c91aa2027c308cd315ec/src/main/scala/com/crealytics/spark/excel/DataLocator.scala#L91

**Comment by koiralo** [comment]
I figured it out the rowId and colInd values are fine in the nest line in map function, but is there a better way of setting Row Missing Cell policy ?
```
      .map(row => {
        colInd.toList.map(row.getCell(_, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK)).to[Vector]
      })
```

**Comment by nightscape** [comment]
I think I was testing the `Row.MissingCellPolicy.CREATE_NULL_AS_BLANK` at some point, but it might lead to data not being `null`ed out correctly where it should be. I don't remember exactly though...
Maybe it would be an option to only do this for the header row?
Also, please check if `row.getCell` is supported by the streaming reader, it might be that it only supports a `cellIterator`.

**Comment by koiralo** [comment]
Yes, I think doing this only for the header row is better, Is there a example of streaming reader, I didn't find it to test for that

**Comment by nightscape** [comment]
The streaming reader gets activated when the `maxRowsInMemory` option is set.
The integration tests always run [with and without `maxRowsInMemory`](https://github.com/crealytics/spark-excel/blob/main/src/test/scala/com/crealytics/spark/excel/IntegrationSuite.scala#L330-L332).
The implementation is in the [`StreamingWorkbookReader`](https://github.com/crealytics/spark-excel/blob/main/src/main/scala/com/crealytics/spark/excel/WorkbookReader.scala#L54) and uses [Excel Streaming Reader](https://github.com/monitorjbl/excel-streaming-reader) which tries to implement the Apache POI API, but throws Exceptions for scenarios it doesn't (yet) support.

**Comment by koiralo** [comment]
@nightscape  How long does running test normally take? it is taking me forever, already more than 2-3 hours.

**Comment by nightscape** [comment]
There's definitely something wrong then. I didn't run the full test suite on my machine for a while, but afair it was a few minutes, maybe 5.

**Comment by quanghgx** [comment]
Hi @datadu-de , @koiralo 
From the work of @nightscape in #210 and then in #389, spark-excel now can handle this case well.

I've just tested with

- Spark excel 0.14.0, build for spark 3.1.2
- Run inside jupyter notebook
- Input file: df_empty_headers_not_working.xlsx, the one @datadu-de shared in the 1st message.

Result (screenshot):
![Screenshot from 2021-09-04 23-12-36](https://user-images.githubusercontent.com/22023385/132101233-53b4f661-4604-4024-bf69-2dc9daf99bb9.png)

Here is the whole scripts:
```python
from pyspark.sql import SparkSession
from pyspark.sql.functions import input_file_name

# Please change to your path!!!
ROOT="/home/quanghgx/spark-excel"

# Assembly or download spark-excel and its dependencies
jars = [
    "/home/quanghgx/spark-excel/target/scala-2.12/spark-excel_2.12-3.1.2_0.14.0+8-4b62d9c5-SNAPSHOT.jar",
    "/home/quanghgx/jars/poi-ooxml-schemas-4.1.2.jar",
    "/home/quanghgx/jars/commons-collections4-4.4.jar",
    "/home/quanghgx/jars/xmlbeans-3.1.0.jar"
]

spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.jars", ",".join(jars)) \
    .getOrCreate()

df = spark.read.format("excel") \
   .option("header", True) \
   .option("inferSchema", False) \
   .option("dataAddress", "A8") \
   .load(f"/home/quanghgx/Desktop/df_empty_headers_not_working.xlsx")

df.show(10)
df.printSchema()
df.count()
```
And the run time should be under a second or two.

Please take a try if you have time. Thank you so much for sharing the detailed test-case and great discussion.
Sincerely,

**Comment by quanghgx** [comment]
Going to resolve this ticket, however, feel free to re-open it!
Sincerely,
