### ISSUE TITLE
Update README :) 

### ISSUE THREAD

**Issue by aestela-brighthealthplan** [crealytics/spark-excel#377]
Hello!

I ran into several issues with this library because I was using version 0.13.1 as specified on the README. I finally came across the closed issue that addressed what I was seeing, and the release that fix was pushed with. Only then did I think to go to Maven repo and see that you had later versions. 

Could you update the README to show the latest version, or point to the maven repo to find the latest version? (And any other cleanup). Hopefully that will save others the few hours it cost me. 

Thanks!

**Comment by nightscape** [comment]
Hi @aestela-brighthealthplan,

that would be a nice first PR 😃 
You can check how the badge in README.md is set for the SNAPSHOT version, add a similar badge for the stable version and mention in the README, that the above versions should be used.

**Comment by AlbertUlysses** [comment]
Hi @nightscape 
If no one is working on this, I can help with it :smile:

**Comment by aestela-brighthealthplan** [comment]
So sorry I missed your response @nightscape ! All yours @AlbertUlysses

**Comment by nightscape** [comment]
Hi @AlbertUlysses, depending on your familiarity with SBT and Github Pages, it would be very nice to publish a micro-site using e.g. https://47degrees.github.io/sbt-microsites/
I assume this would allow interpolating the currently published versions into the HTML, so it can't be forgotten anymore 😉

**Comment by quanghgx** [comment]
Resolve this issue, as #420 is merged. Thanks to @pjfanning
