### ISSUE TITLE
An error occurred while calling o3682.save. : shadeio.poi.ss.formula.FormulaParseException: Unused input [DKK / 2] after attempting to parse the formula [47050 DKK / 2]

### ISSUE THREAD

**Issue by maniksha1** [crealytics/spark-excel#398]
below code is working on UAT but not working in prod.

dw_mcr_report.write.mode("overwrite").format("com.crealytics.spark.excel").option("header", "True").option("treatEmptyValuesAsNulls", "false").option("inferSchema", "false").option("addColorColumns", "true").save(destpath)

Below are the error getting error on production :

An error occurred while calling o3682.save. : shadeio.poi.ss.formula.FormulaParseException: Unused input [DKK / 2] after attempting to parse the formula [47050 DKK / 2]

Note : same code is working properly in UAT.

**Comment by nightscape** [comment]
I guess your best option is to search with the same error in Apache POI.

**Comment by maniksha1** [comment]
tx nightscape, issue resolved.

**Comment by maniksha1** [comment]
> I guess your best option is to search for the same error in Apache POI.

tx nightscape, issue resolved.

**Comment by nightscape** [comment]
If you don't mind, it would be great if you could post the solution here in case someone else runs into it.

**Comment by maniksha1** [comment]
> If you don't mind, it would be great if you could post the solution here in case someone else runs into it.

 As we are processing data from SQL. it was data issue, Specials character(=) was available in prod SQL,
