### ISSUE TITLE
Number of rows in dataframe is wrong

### ISSUE THREAD

**Issue by olemara** [crealytics/spark-excel#424]
## Expected Behavior
Reading in excel file to dataframe

```
df_local = spark.read.format("com.crealytics.spark.excel")\
    .option("header", "true")\
    .option("dataAddress", "sheetname'!A21")\
    .option("keepUndefinedRows", False)\
.load(raw_excel_path)
```

Results in dataframe containg rows with data.

## Current Behavior
```
df_local = spark.read.format("com.crealytics.spark.excel")\
    .option("header", "true")\
    .option("dataAddress", "sheetname'!A21")\
    .option("keepUndefinedRows", False)\
.load(raw_excel_path)

df_local.count()
```
Results in a dataframe with around 1000 rows that contains no data. There should only be around 200 rows:

When printing the rows, the all have None values.

```
None | None | None | None | None | None | None | None | None | None | ... | None | None | None | None | None | None | None | None | None | None
None | None | None | None | None | None | None | None | None | None | ... | None | None | None | None | None | None | None | None | None | None
None | None | None | None | None | None | None | None | None | None | ... | None | None | None | None | None | None | None | None | None | None
None | None | None | None | None | None | None | None | None | None | ... | None | None | None | None | None | None | None | None | None | None
None | None | None | None | None | None | None | None | None | None | ...


```

How can I avoid this?

## Your Environment
* Spark version and language (Scala, Java, Python, R, ...)
 spark-3.1.2-bin-hadoop2.7
* Spark-Excel version:
com.crealytics:spark-excel_2.12:0.14.0
* Operating System and version, cluster environment, ...:
Ubuntu, on local computer

**Comment by quanghgx** [comment]
Hi @olemara 
Can you change the `format("com.crealytics.spark.excel")` to `format("excel")` and try again?

If the issue is still there, please help share an excel file that we can use to reproduce given issue. (Please remove sensitive information there, if any).

Sincerely,

**Comment by olemara** [comment]
Hi @quanghgx ,

And thanks for such a quick reply!

I have tried changing the format to 'excel' without luck. Anonymizing the excel would be a lot of work, but a piece of information that might help: Reading the same excel with pandas, gives me the right number of rows, which is 247. Using  'com.crealytics.spark.excel', or just 'excel', gives exactly 1000 more rows.

**Comment by quanghgx** [comment]
Hi @olemara ,
In Excel file, a cell might look blank, but, if we ever "touch" it, like define some property, it will turn into defined.

- Under the hood, reading Excel is iterating between "defined" rows. Detail in (3) bellow.
- There are couple solutions, those I can think of in (2)
- Maybe, we can add an option "skipBlankRows" to push the .dropna() down to data source filter. Please share with us what do you think, after review (1,2,3), @olemara?

Hope this helps.

---------------------------------------------
PS: Detail for (1,2 and 3)
1. Please confirm that, **are your first 247 rows are loaded correc**tly with spark-excel?

2. If (1) is yes, then I can think of two solutions:

**Solution A:** Skip all-null rows with [DataFrame.dropna](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.dropna.html)
```python
spark.read.format("excel") \
   .option("header", True) \
   .option("inferSchema", True) \
   .load(f"/home/quanghgx/Downloads/olemara_example.xlsx") \
   .dropna(how="all") \
   .show(100)
```

**Solution B:** Use RowID and filter anything after a certain rows
```python
spark.read.format("excel") \
   .option("header", True) \
   .option("inferSchema", True) \
   .option("columnNameOfRowNumber", "RowID") \
   .load(f"/home/quanghgx/Downloads/olemara_example.xlsx") \
   .filter("RowId < 26") \
   .show(100)
```

3. Let use an example to demonstrate the blank, but defined cells.

Created a fairly simple excel file (with google spreadsheet, then download)
[olemara_example.xlsx](https://github.com/crealytics/spark-excel/files/7267139/olemara_example.xlsx)

Row 24,25,27: no touch at all (will be keep with [keepUndefinedRows= True](https://github.com/crealytics/spark-excel/wiki/Examples:-With-Row-Number-&-Undefined-Rows#keeping-undefined-rows))
Row 28,29: select and change back ground color

(a) With
```python
spark.read.format("excel") \
   .option("header", True) \
   .option("inferSchema", True) \
   .load(f"/home/quanghgx/Downloads/olemara_example.xlsx") \
   .show(100)
```
We will have
```bash
+-------+----+
|   col1|col2|
+-------+----+
|   lion| 100|
|    cat|  10|
|chicken|  50|
|   null|null|
|   null|null|
+-------+----+
```
Last two rows are actually defined in excel term.

(b), we can see it more clear with:
```python
   .option("columnNameOfRowNumber", "RowID") \
```
result:
```bash
+-----+-------+----+
|RowID|   col1|col2|
+-----+-------+----+
|   21|   lion| 100|
|   22|    cat|  10|
|   25|chicken|  50|
|   27|   null|null|
|   28|   null|null|
+-----+-------+----+
```

**Comment by quanghgx** [comment]
And here is the notebook that I used for testing this case:
[olemara_424.pdf](https://github.com/crealytics/spark-excel/files/7267435/olemara_424.pdf)

**Comment by olemara** [comment]
Thank you very much for this. I will test as soon as I have time and get back to you.

**Comment by quanghgx** [comment]
Hi @olemara , any update on this issue?

**Comment by quanghgx** [comment]
Thanks @olemara 
I am going to close the ticket, feel free to reopen it.
Have a nice weekend.
