### ISSUE TITLE
Testing spark-excel again coming spark 3.2 release

### ISSUE THREAD

**Issue by quanghgx** [crealytics/spark-excel#427]
Tasks:

- [x] Testing again coming spark-3.2 release, as of October 3rd, 2021: compile, unit-tests
- [x] Update readme and related documents
- [x] Release prebuilt binary, that works with for spark-3.2

**Comment by nightscape** [comment]
This frameless PR might give us a clue:
https://github.com/typelevel/frameless/pull/573/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91

**Comment by quanghgx** [comment]
Hi @nightscape , please help review this MR when you have time.

**Comment by nightscape** [comment]
I just changed the build to publish for all Spark version and also Scala 2.13 + Spark 3.2.0.
I'll release `0.16.0` in a minute 👍
