### ISSUE TITLE
File with a large number of records taking too long to be read and written as a table

### ISSUE THREAD

**Issue by sidrahsayyad** [crealytics/spark-excel#440]
I'm trying to ingest an excel file that contains 58 columns and 906188 rows. The total size of the file is around 258 MB.
This is being done using v0.11 of the library on AWS EMR that consists of 1 master and 3 core nodes all belonging to the r5.2xlarge family.

I've tried changing the value of maxRowsInMemory, but the performance remains around 1.5 hours. Can anyone please help understand what can be done to overcome this performance issue.

**Comment by sidrahsayyad** [comment]
Is there anything one can do to make this read faster ? Playing with maxRowsInMemory did not help.

**Comment by nightscape** [comment]
Do you have any chance to upgrade to 0.14? A lot has changed since 0.11, maybe performance was improved as well.

**Comment by EnverOsmanov** [comment]
The issue with large files was resolved in [v0.13.5](https://github.com/crealytics/spark-excel/releases/tag/v0.13.5).
