### ISSUE TITLE
support scala 2.13?

### ISSUE THREAD

**Issue by ASchmidt84** [crealytics/spark-excel#450]
Is their a plan to support scala 2.13?

**Comment by nightscape** [comment]
Yes, sometime after https://github.com/crealytics/spark-excel/issues/427

**Comment by nightscape** [comment]
Cross-publishing to Scala 2.13 has just landed. Will release `0.16.0` once the tests are green.

**Comment by nightscape** [comment]
Release + build is on its way: https://github.com/crealytics/spark-excel/releases/tag/v0.16.0
@ASchmidt84 it would be great if you could test this and report any problems in new issues.
Will close this one now.
