### ISSUE TITLE
Cannot load multiple paths 

### ISSUE THREAD

**Issue by dutrow-qualytics** [crealytics/spark-excel#462]
Version `"com.crealytics:spark-excel_2.12:0.14.0"`

```
val identifiers = Seq("s3a://bucket/wb1.xlsx", "s3a://bucket/wb1.xlsx")

spark.read
            .options(options)
            .format("com.crealytics.spark.excel")
            .load(identifiers.map(_.toString): _*)

            ...
``` 

This invokes `DataFrameReader.load(paths: String*)`
Which invokes  `loadV1Source(paths: _*))`

If there is a single path, it passes Nil as the finalPaths and packs the "path" with a single URI. However, if there are multiple paths, the finalPaths contain the array, and the "path" option isn't created. See below:

```
  private def loadV1Source(paths: String*) = {
    val legacyPathOptionBehavior = sparkSession.sessionState.conf.legacyPathOptionBehavior
    val (finalPaths, finalOptions) = if (!legacyPathOptionBehavior && paths.length == 1) {
      (Nil, extraOptions + ("path" -> paths.head))
    } else {
      (paths, extraOptions)
    }
    
        // Code path for data source v1.
    sparkSession.baseRelationToDataFrame(
      DataSource.apply(
        sparkSession,
        paths = finalPaths,
        userSpecifiedSchema = userSpecifiedSchema,
        className = source,
        options = finalOptions.originalMap).resolveRelation())
  }
  
```  

This eventually arrives at com.crealytics.spark.excel.WorkbookReader

```
  def apply(parameters: Map[String, String], hadoopConfiguration: Configuration): WorkbookReader = {
    def readFromHadoop(location: String) = {
      val path = new Path(location)
      FileSystem.get(path.toUri, hadoopConfiguration).open(path)
    }
    parameters match {
      case WithLocationMaxRowsInMemoryAndPassword(Seq(location), Seq(Some(maxRowsInMemory), passwordOption)) =>
        new StreamingWorkbookReader(readFromHadoop(location), passwordOption, maxRowsInMemory.toInt)
      case WithLocationMaxRowsInMemoryAndPassword(Seq(location), Seq(None, passwordOption)) =>
        new DefaultWorkbookReader(readFromHadoop(location), passwordOption)
    }
  }
```
    
Since `WithLocationMaxRowsInMemoryAndPassword = MapIncluding(Seq("path"), optionally = Seq("maxRowsInMemory", "workbookPassword"))`, the missing "path" in the options means that the match fails, causing a MatchError
            
To get around this, I have to spoon feed the load operation one at a time and then do a reduce/union action afterward.

```
val identifiers = Seq("s3a://bucket/wb1.xlsx", "s3a://bucket/wb1.xlsx:)

val dataframes = identifiers.map(id =>
  spark.read
            .options(options)
            .format("com.crealytics.spark.excel")
            .load(id)
)
dataframes.reduce(_ union _)
     
```

Once you've implemented this, supporting globs should be easy.

```
val identifiers = 
    org.apache.hadoop.fs.FileSystem
      .get(baseUri), spark.sparkContext.hadoopConfiguration)
      .globStatus(new Path(globIdentifier))
      .map(p => p.getPath)
```

**Comment by quanghgx** [comment]
Hi @dutrow-qualytics 
Thanks for your feed back and solution with data frame union.

There are actually two implementations of spark-excel data source. Could you please try again with:
`.format("excel")`
Yes, just "excel"

There are some document here: [Examples: Load Multiple Files](https://github.com/crealytics/spark-excel/wiki/Examples:-Load-Multiple-Files#with-glob-pattern)

**Comment by dutrow-qualytics** [comment]
Interesting. The `"excel"` implementation appears to work. The availability of these two options is not well documented. I recommend updating the introductory pages to describe these two implementations and the feature set for each.

**Comment by quanghgx** [comment]
Thanks @dutrow-qualytics for your update.

You are right, after https://github.com/crealytics/spark-excel/pull/389 we need to figure out when (mostly) and how to switch to V2 by default. Will update wiki and the landing page (README.md) as well.

Would like to resolve this ticket.
