### ISSUE TITLE
spark-excel doesn't take into account the 'spark.sql.datetime.java8API.enabled' conf added in spark 3

### ISSUE THREAD

**Issue by cristichircu** [crealytics/spark-excel#463]
Spark 3 added support for working with java.time.LocalDate/Instant instead of java.sql.Date/Timestamp by setting the [spark.sql.datetime.java8API.enabled](https://github.com/apache/spark/blob/3565c3aff9be6cc4e9d6faf9625c0c40ea5fa8d4/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala#L3014) to true. However this doesnt reflect when reading data from excel using-spark excel and that will cause issues.

## Expected Behavior
Read date and timestampt using the new api when the flag is enabled

## Current Behavior
Dates and timestamps are read using the old API. Exception I ran into is somehting like:
```
java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.sql.Date is not a valid external type for schema of date
.....
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, DateType, localDateToDays, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 4, Date), DateType), true, false) AS Date#3531
.....
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:213)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:195)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at org.apache.spark.sql.execution.columnar.DefaultCachedBatchSerializer$$anon$1.hasNext(InMemoryRelation.scala:118)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)

```
## Possible Solution
I tracked down my particular issue [here](https://github.com/crealytics/spark-excel/blob/dfbd768af13f704f8859e8c70bb62485b9ca6cc4/src/main/scala/com/crealytics/spark/excel/DataColumn.scala#L102) however I'm not sure if there are other places in the sourcode where a fix would be needed. If we can can get our hands on the spark config here we could return either Date or LocalDate

I also noticed there's a v2.excel package. Is that a new version of spark-excel? Is it ready for use? I couldn't find anything about it in the docs.
## Steps to Reproduce (for bugs)
Read any excel file with dates or timestamps having spark.sql.datetime.java8API.enabled set to true in spark conf

## Context
Already covered

## Your Environment
* Spark version and language (Scala, Java, Python, R, ...): spark 3.1.1 with Java 11
* Spark-Excel version: com.crealytics:spark-excel_2.12:0.14.0

**Comment by quanghgx** [comment]
Hi @cristichircu 

You are right, v2 spark-excel are already using new date&time API: https://github.com/crealytics/spark-excel/blob/main/src/main/3.1/scala/com/crealytics/spark/v2/excel/ExcelDateTimeStringUtils.scala
There are some more detail here: https://github.com/crealytics/spark-excel/pull/389

Could your please try again with .format("excel")? this will route to V2 implementation.
Sincerely,

**Comment by cristichircu** [comment]
Thanks for pointing me in the right dirrection, @quanghgx! I got rid of the error by replacing the format option. 
At a first glance it looks like there's no more support for org.apache.spark.sql.types.DateType and org.apache.spark.sql.types.DecimalType (values are null after reading when providing a schema like I used to). I started having a look in [ExcelInferSchema](com.crealytics.spark.v2.excel.ExcelInferSchema#inferTypeOfStringValue) to figure out what's hapening. The first thing I notice is that DateType doesn't seem to be handled there. Any hint on what I can do to correctly read Date and Decimal types would be appreciated.
Thanks!

**Comment by nightscape** [comment]
@cristichircu afaik, dates are actually stored as numbers in Excel, and only the meta-information about a cell type makes it being interpreted as date.
But you could try debugging and setting a breakpoint to see what happens with a date cell.

**Comment by cristichircu** [comment]
Thanks, @nightscape!
For my Decimal columns I was able to figure it out. An exception is thrown [here](https://github.com/crealytics/spark-excel/blob/0dc8aa3eb336bb5977467b984e383d2f72bc4056/src/main/scala/com/crealytics/spark/v2/excel/ExcelParser.scala#L237) saying "Cannot get a STRING value from a NUMERIC cell". Seems pretty weird to me that poi would choose to throw an error in that case but hey.. it is what it is. Because of this all Decimal values are ignored.
I'm still looking into what the problem is with Date values

**Comment by quanghgx** [comment]
Thanks @cristichircu 
Look like you found a bug. Could you please share a simple excel file with Date and Decimal column so we can reproduce the issue? and put it into unit-test as well.

**Comment by cristichircu** [comment]
Thanks, @quanghgx! 
Here's an example: [example.xlsx](https://github.com/crealytics/spark-excel/files/7616780/example.xlsx). I need to mention that I'm not using schema inference and I'm passing a schema containing [org.apache.spark.sql.types.DataTypes#StringType, org.apache.spark.sql.types.DataTypes#createDecimalType(23, 10), org.apache.spark.sql.types.DataTypes#DateType].
Thank you!

**Comment by quanghgx** [comment]
Hi @cristichircu and @nightscape 

MR for this issue is ready for review: ​https://github.com/crealytics/spark-excel/pull/475
Please take a look when you have time.

Sincerely,

**Comment by cristichircu** [comment]
Thanks for all your help, @quanghgx!

**Comment by cristichircu** [comment]
Thanks for all the effort you put into this @quanghgx and @nightscape!

I'm going to leave the question from the merge request here as well so that maybe one of you can share your thougths: I noticed that you're using java.sql.Date [here](https://github.com/crealytics/spark-excel/blob/4afbe773e4329b59855266c2e26fbda63efea1c3/src/main/scala/com/crealytics/spark/v2/excel/ExcelParser.scala#L280). I'm not familiar with the codebase but will this work if spark.sql.datetime.java8API.enabled is set to true (and spark works with LocalDate and Instant instead of their java.sql counterparts)?

Any ideas when you're planning the next release?

Thank you!

**Comment by quanghgx** [comment]
Hi @cristichircu 

For the java.sql.Date part:
```java
DateTimeUtils.fromJavaDate(new java.sql.Date(datum.getDateCellValue().getTime))
```
You are right, we can refactor this part. There are no specific reason for this, just couple of though:
* in V2, we do prefer reusing spark's facility as much as possible. It happened to me that DateTimeUtils has a method that can be used.
* For this particular case, we can just divide the cell getTime value to a certain constant and return.

About the java8API, let me do some checking and get back to you.
Sincerely,

**Comment by cristichircu** [comment]
I noticed that 0.16 is out and it contains the fix. Just tested it and it worked as expected.

I bumped into isse [480](https://github.com/crealytics/spark-excel/issues/480) caused by the apache poi upgrade. Taking a cue from the fix [here](https://github.com/crealytics/spark-excel/pull/465/commits/c3286e1b367c782fd6e17c4afba929a8ec0dd44c#diff-f4bbb03242328fac2205e4089aacd1344978fb27c5e554bc706a8b5f0ba3a3f6R34) I managed to get i working localy by adding this to my code (not sure if this would work in a production setup since I don't know if this code is called from the executor):
`
WorkbookFactory.addProvider(new HSSFWorkbookFactory());
WorkbookFactory.addProvider(new XSSFWorkbookFactory());
`

To me it seems that the fix was only made for the original format and it just needs to be added to v2. Not sure if this would require any other changes.

Thanks for all your help @quanghgx and @nightscape !

**Comment by nightscape** [comment]
Hey @cristichircu, cool that it works now and good pointer about the initialization being done only in the v1 version.
If you dare to, it would be great if you could create a PR to fix this!
Bonus points if you create a `object PoiInitializer` which makes the above calls and gets shared between v1 and v2 😃

**Comment by cristichircu** [comment]
nice way of putting it :) I added the [pull request](https://github.com/crealytics/spark-excel/pull/491)
couldn't figure out where common code between v1 and v2 should reside so I didn't get the bonus (yet)
