### ISSUE TITLE
Improvement to documentation on how to use spark-excel in PySpark

### ISSUE THREAD

**Issue by rudolph-m** [crealytics/spark-excel#477]
## Expected Behavior
> I am new to Spark and when I found this library I struggled to integrate it in my project.  I googled how to import the library in python but the information I found online was rather terse so in the end I gave up and just converted the file to csv.
> I am hoping to find a way to import this library in Python to use it with PySpark as I am sure other beginners are going to run into this issue in the future.

## Environment
> Spark 3.0
> Python 3.6.7

**Comment by nightscape** [comment]
Hi @rudolph-m, thanks for opening this issue.
Does this Wiki page help?
https://github.com/crealytics/spark-excel/wiki
If not, what information is missing there?

**Comment by rudolph-m** [comment]
yes this definitely helps a lot.

**Comment by quanghgx** [comment]
Going to resolve this ticket. However, please help a hand on the wiki/readme and documentation in general for spark-excel.
