### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by sushantkhanayat** [crealytics/spark-excel#51]
Do we have any Excel or spreadsheet proccessing dependency jar for Spark version 1.6.

I am facing error 
"java.lang.NoSuchMethodError: scala.util.matching.Regex.unapplySeq(Ljava/lang/CharSequence;)Lscala/Option;
at com.crealytics.spark.excel.ExcelRelation$$anonfun$4.apply(ExcelRelation.scala:113)"

while processing it with spark 1.6.

**Comment by nightscape** [comment]
This plugin is not tested with Spark 1.6.
We also won't invest time to make it compatible as we have long switched to Spark 2+.
Sorry...
