### ISSUE TITLE
Rows are returned in incorrect order on cluster

### ISSUE THREAD

**Issue by davidw76** [crealytics/spark-excel#59]
When reading an excel file on a cluster, the rows in the RDD are out of order

**Comment by davidw76** [comment]
possible fix..
`val rdd = sqlContext.sparkContext.parallelize(result.map(Row.fromSeq), 1)`
i.e. limit the rdd to a single partition

**Comment by nightscape** [comment]
Another option might be to have a virtual `row_number` attribute that gets added if included in the `requiredColumns`. Then you're free to sort by it or ignore it if you want full parallelization.

**Comment by quanghgx** [comment]
Hi @davidw76 
Please help check if the spark-excel v0.14.0 (and up) with additional row_number column can handle your case?
Sincerely,

**Comment by quanghgx** [comment]
Feel free to reopen this ticket incase of further issues.
Sincerely,
