### ISSUE TITLE
Is there a parameter to read excel by columns?

### ISSUE THREAD

**Issue by JoyChen037** [crealytics/spark-excel#591]
Hi, thank you for this library. 
1. I was wondering if there is a parameter specifically to read excel data by column numbers? 
2. Also, I am handling some excels with row orientation unfortunately, would it be possible to read them accurately with this library? 

Thank you in advance for your help!

**Comment by nightscape** [comment]
Hi @JoyChen037, the answer might be too late, but here we go nonetheless:

1. Not directly. If you do a `.option("headers", "false")` you should get columns named `c1`, `c2`, ...
2. This is currently not possible. If someone wants to create a PR for it, we're happy to review and merge.
