### ISSUE TITLE
[BUG] Writing excel dataframe to Azure Storage container

### ISSUE THREAD

**Issue by s0y03gy** [crealytics/spark-excel#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to write dataframe with excel format to azure storage account. The same works for csv, and fails for excel format alone.
`dataFrame
      .coalesce(1)
      .write
      .format("com.crealytics.spark.excel")
      .option("header", "true")
      .option("escape", "\"")
      .option("quote", "\"")
      .mode(SaveMode.Append)
      .save(destPath)`
      
      destPath has azure storage account's container path.
      
      I have done setting in sparksession too.
      spark.conf.set(
  "fs.azure.account.key.<storage-account-name>.blob.core.windows.net",
  "<storage-account-access-key>")
  
  I am getting org.apache.hadoop.fs.azure.AzureException and getting excception in container not found. 
  But the same path work for csv and write the dataframe in csv format.
  
  I also referred to the issue - https://github.com/crealytics/spark-excel/issues/105

### Environment

```markdown
- Spark version:
- Spark-Excel version:
- OS:
- Cluster environment
```

**Comment by nightscape** [comment]
Can you try with `.format("excel")`? That uses the new v2 API and shares more code with the CSV implementation.

**Comment by s0y03gy** [comment]
I tried setting azure blob key and value in sparksession's hadoop configuration, and it worked.
