### ISSUE TITLE
v2 datasource only seems to support writing files to HDFS - and not to local files

### ISSUE THREAD

**Issue by pjfanning** [crealytics/spark-excel#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/crealytics/spark-excel/blob/main/src/main/scala/com/crealytics/spark/v2/excel/ExcelGenerator.scala#L165

Above code creates a HDFS output stream based on a path variable.

It seems to me it is at least as useful to support writing to a java.io.FileOutputStream so that complete files can be written out.

### Environment

```markdown
- Spark version:
- Spark-Excel version:
- OS:
- Cluster environment
```

**Comment by pjfanning** [comment]
Yes, my point is about the usefulness of also supporting local files (non-HDFS).

**Comment by nightscape** [comment]
Afaik, the HDFS methods support reading and writing local files.
The question is how the provided path gets interpreted, but you should be able to force spark-excel by providing a path like `file:///my/local/path`.

**Comment by pjfanning** [comment]
@nightscape I tried setting the 'path' for the v2 datasource to /Users/pj.fanning/code/spark-excel.xlsx and to file:///Users/pj.fanning/code/spark-excel.xlsx

In both cases, this resulted in the data being saved in a directory called spark-excel.xlsx in a format like.

```
drwxr-xr-x    6 pj.fanning  staff    192 14 Aug 20:53 .
drwxr-xr-x  324 pj.fanning  staff  10368 14 Aug 20:53 ..
-rw-r--r--    1 pj.fanning  staff      8 14 Aug 20:53 ._SUCCESS.crc
-rw-r--r--    1 pj.fanning  staff     40 14 Aug 20:53 .part-00000-a349c483-88ea-4052-94f3-77cdb7c8fdad-c000.xlsx.crc
-rw-r--r--    1 pj.fanning  staff      0 14 Aug 20:53 _SUCCESS
-rw-r--r--    1 pj.fanning  staff   3819 14 Aug 20:53 part-00000-a349c483-88ea-4052-94f3-77cdb7c8fdad-c000.xlsx
```

I guess what I'm proposing is that a separate property is make available, maybe "saveAsLocalFile" (default false). So with false, the existing HDFSOutputStream is created and with true, a FileOutputStream is created (and the in the latter case, the path is the absolute file location including the directory).

HDFS output:
```
      df_source.write
        .format("excel")
        .option("dataAddress", dataAddress)
        .mode(SaveMode.Overwrite)
        .save(path)
```

File output:
```
      df_source.write
        .format("excel")
        .option("dataAddress", dataAddress)
        .option("saveAsLocalFile", true)
        .mode(SaveMode.Overwrite)
        .save(path)
```

**Comment by nightscape** [comment]
v1 operates this way. It would be nice to be able to do the same thing with v2, then we could get rid of v1 at some point.
I'm not sure about a `saveAsLocalFile` parameter. It seems complects (as in [Simple made easy by Rich Hickey](https://www.youtube.com/watch?v=SxdOUGdseq4)) to orthogonal concerns:
Writing to a single or multiple files and writing to HDFS or local.
Maybe we could assume that if the file path ends with `.xlsx`, the user actually wants a single file with that extension, and making sure that paths starting with `file:///` correctly stores to local disk?
That way we wouldn't need another parameter and could handle all 4 combinations of single/multiple x HDFS/local.

**Comment by pjfanning** [comment]
I'll close this.
