### ISSUE TITLE
FileNotFoundException when try to launch Job with master yarn and deploy-mode cluster

### ISSUE THREAD

**Issue by rahulsquid** [crealytics/spark-excel#63]
I am using Hadoop cluster with Yarn resource manager. When I run the job in fully distributed mode `master yarn & deploy-mode cluster` the job fails with below exception. However, when I change "deploy-mode" to client it runs successfully.

> ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637) Caused by: java.io.FileNotFoundException: /mapr/Helios/cxpdi/datasets/test/data/TEST/INPUT/data.xls (No such file or directory) at java.io.FileInputStream.open0(Native Method) at java.io.FileInputStream.open(FileInputStream.java:195) at java.io.FileInputStream.(FileInputStream.java:138) at java.io.FileInputStream.(FileInputStream.java:93) at com.crealytics.spark.excel.ExcelRelation.(ExcelRelation.scala:28) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:31) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:7) at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)

I would suggest, instead of `java.io.FileInputStream` use org.apache.hadoop.fs.FileSystem api to open stream when master yarn and deploy is cluster.

**Comment by nightscape** [comment]
We're already doing that:
https://github.com/crealytics/spark-excel/blob/1ffcfb07bc98f21a3073c4939775778bc8cb1d69/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L51
Are you sure the file is accessible in that location?
Also, I think we can only handle `.xlsx` files.

**Comment by rahulsquid** [comment]
yes. file is accessible and it's in .xlsx format. As I mentioned it works when I run driver in local mode.

**Comment by nightscape** [comment]
Can you find out on which cluster node the exception is thrown and use the hadoop CLI to check if the file can be read from there?
https://hadoop.apache.org/docs/r2.4.1/hadoop-project-dist/hadoop-common/FileSystemShell.html
This problem really doesnt really seem to be related to spark-excel...
