### ISSUE TITLE
Not reading all columns

### ISSUE THREAD

**Issue by jj6144** [crealytics/spark-excel#64]
I am reading a sheet from an excel file which has 6 columns. I am getting 5 columns in the resulting data frame. I added start and end columns as 0 and 5. Still I am not getting the last column in the data frame. This code was working before. 
val df = spark.read.format("com.crealytics.spark.excel")
        .option("sheetName","MRI_NPM")
        .option("useHeader", "false")
        .option("startColumn",0)
        .option("endColumn",5)
        .load(configFilePath)

**Comment by nightscape** [comment]
So you're saying the problem happens with and without `startColumn` and `endColumn`?
Does your file contain headers for all columns?

**Comment by nightscape** [comment]
Possibly fixed in `0.9.16`. Please check and reopen with more information if this still happens.
