### ISSUE TITLE
skip rows from excel sheet

### ISSUE THREAD

**Issue by kali786516** [crealytics/spark-excel#65]
Hi , 

my excel file has rows on the top which needs to be skipped , can I do it using this library ?

Thanks
Sri

**Comment by d4rkc0de** [comment]
Any updates on this ?

**Comment by nightscape** [comment]
Would the solution I described in https://github.com/crealytics/spark-excel/issues/40 work for you?
Do those first rows contain headers?

**Comment by kali786516** [comment]
Thanks for coming back, no the excel file don’t have headers on the first row so my headers and data is from row 5 wat I have in the row 1 is excel report name.

Thanks 
Sri

**Comment by nightscape** [comment]
Ok, then I guess you have to introduce a new `skipRows` configuration parameter which is taken into account in the `getExcerpt` method: https://github.com/crealytics/spark-excel/blob/1ffcfb07bc98f21a3073c4939775778bc8cb1d69/src/main/scala/com/crealytics/spark/excel/ExcelRelation.scala#L63
Do you mind creating a PR?

**Comment by kali786516** [comment]
PR ? What does it mean ? 

Thanks 
Sri

**Comment by nightscape** [comment]
Released as `0.9.16`.
