### ISSUE TITLE
getErrorCellValue ignore NotSupportedException option

### ISSUE THREAD

**Issue by TomLous** [crealytics/spark-excel#66]
It would be awesome if there was an option for errors in excelsheets not to throw exceptions (NotSupportedException), but could be handled as null values with some log message that certain cells have been skipped.

**Comment by quanghgx** [comment]
Hi @TomLous 
Thanks for your suggestion. Spark-excel has new `useNullForErrorCells` [option](https://github.com/crealytics/spark-excel/wiki#spark-excel-options) from version 0.14.0 (and up). 
Please take a try and feel free to reopen this ticket.
Sincerely,
