### ISSUE TITLE
[QUESTION] read all sheets of excel

### ISSUE THREAD

**Issue by cometta** [crealytics/spark-excel#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

May i know if i don't use `dataAddress` as option
```
df = spark.read \
    .format("com.crealytics.spark.excel") \
    .option("header", "true") \
    .load("/path/file.xls")
```
does this auto retrieve all sheets into dataframe?

### Environment

```markdown
- Spark version:
- Spark-Excel version:
- OS:
- Cluster environment
```

**Comment by nightscape** [comment]
No, spark-excel currently always retrieves only data from one sheet.

**Comment by nightscape** [comment]
This might be helpful though: https://github.com/crealytics/spark-excel/issues/176#issuecomment-567545939
