### ISSUE TITLE
ERROR: java.lang.IllegalStateException: Cannot get a text value from a numeric cell

### ISSUE THREAD

**Issue by luodin007** [crealytics/spark-excel#7]
I used this lib, but had a error with apache.poi. Can not read excel with number
```
[info]   java.lang.IllegalStateException: Cannot get a text value from a numeric cell
[info]   at org.apache.poi.hssf.usermodel.HSSFCell.typeMismatch(HSSFCell.java:640)
[info]   at org.apache.poi.hssf.usermodel.HSSFCell.getRichStringCellValue(HSSFCell.java:717)
[info]   at org.apache.poi.hssf.usermodel.HSSFCell.getStringCellValue(HSSFCell.java:700)
[info]   at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:117)
[info]   at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:117)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:742)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
```  

excel sample:
```
Michael	29
Andy	30
Justin	19
```

**Comment by sidrahsayyad** [comment]
We are getting this issue as well. Why was this closed ?

**Comment by nightscape** [comment]
Are you using a custom schema? If so, does it specify the column type correctly?
Are you using `.option("inferSchema", "true")`? If not, can you try with this option?

**Comment by oushnikdey** [comment]
Even i am facing similar issue. I am not using custom schema. Also, using .option("inferSchema", "true") did not help.

**Comment by nightscape** [comment]
Can one of you upload a minimal example Excel file somewhere along with the minimal code to reproduce this problem?

**Comment by saadali5997** [comment]
Hi @nightscape,
I have created [this](https://github.com/crealytics/spark-excel/issues/137) issue again with the information which was missing here. Please look into it when you get the chance.
