### ISSUE TITLE
Issues with date column in excel with format dd/mm/yyyy

### ISSUE THREAD

**Issue by vale9003** [crealytics/spark-excel#71]
I'm trying to create a dataframe from a large excel and I have a column that it has a format like this.
mm/dd/yyyy
I've tryed to create a custom schema for this column using StringType, and DateType, but none of these have worked.
If I don't set any schema I receive an error like this; "Exception in thread "main" java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell"

I'm loading the dataframe like this:
  val df = dataFrameReader.format("com.crealytics.spark.excel")
      .option("sheetName", "Hoja1")
      .option("useHeader", "true") // Required
      .option("treatEmptyValuesAsNulls", "true") // Optional, default: true
      .option("inferSchema", "true") // Optional, default: false
      //.option("addColorColumns", "true") // Optional, default: false
      .option("startColumn", 1) // Optional, default: 0
      //.option("endColumn", 99) // Optional, default: Int.MaxValue
      .option("timestampFormat", "MM-dd-yyyy HH:mm:ss") // Optional, default: yyyy-mm-dd hh:mm:ss[.fffffffff]
      .option("maxRowsInMemory", 1000) // Optional, default None. If set, uses a streaming reader which can help with big files
      //.option("excerptSize", 10) // Optional, default: 10. If set and if schema inferred, number of rows to infer schema from
      //.schema(myCustomSchema) // Optional, default: Either inferred schema, or all columns are Strings
      .schema(schema)
      .load( s"hdfs://${fileName}")

My custom schema:
  val schema = StructType(
      List(
        StructField("NroTramite", LongType, true),
        StructField("FchAlta", DateType, true),
        StructField("HraAlta", StringType, true),
        StructField("UsrAlta", StringType, true),
        StructField("Estado", StringType, true),
        StructField("Proceso", StringType, true),
        StructField("Cliente", LongType, true),
        StructField("Razon Social", StringType, true),
        StructField("RelCnt", LongType, true),
        StructField("Mid", LongType, true),
        StructField("Contrato", LongType, true),
        StructField("PlanComercial", StringType, true),
        StructField("Categ", StringType, true),
        StructField("SubCateg", StringType, true),
        StructField("Tecnologia", StringType, true),
        StructField("AgPromotorPlnPrincipal", StringType, true),
        StructField("AgPromotorProducto", StringType, true),
        StructField("ProdExt", IntegerType, true),
        StructField("NombreProdExterno", StringType, true),
        StructField("AgVenta", IntegerType, true),
        StructField("NombreAgVenta", StringType, true),
        StructField("OrigSisExterno", IntegerType, true),
        StructField("FlagAcraTercero", StringType, true),
        StructField("RelCntquePaga", IntegerType, true)
      )
    )

The error that I get when I use this schema:
Exception in thread "main" java.lang.NumberFormatException: For input string: "Fch Alta"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at scala.collection.immutable.StringLike$class.toDouble(StringLike.scala:284)
        at scala.collection.immutable.StringOps.toDouble(StringOps.scala:29)
        at com.crealytics.spark.excel.ExcelRelation.numericValue$lzycompute$1(ExcelRelation.scala:111)
        at com.crealytics.spark.excel.ExcelRelation.numericValue$1(ExcelRelation.scala:108)

I look forward for your answers, thanks in advance.

**Comment by davidw76** [comment]
Make sure all values for FchAlta are in the same format (every row).
It sounds like some rows might be stored as strings and others as dates or numbers in the Excel file.

**Comment by nightscape** [comment]
Looks like this problem is solved?
If not, please reopen.
