### ISSUE TITLE
Allow reading multiple files specified as a list OR by a pattern 

### ISSUE THREAD

**Issue by pooja-murarka** [crealytics/spark-excel#74]
Currently Excel library don't allow to read multiples files specified as a pattern OR as a list ( formats has been shown below). These formats are supported for reading delimited files by DataFrameReader

 reader.format( "com.crealytics.spark.excel" )
          .option( "useHeader", true )
          .option( "timestampFormat", "MM-dd-yyyy HH:mm:ss" )
          .load( "/Data*.xlsx" );
OR

 reader.format( "com.crealytics.spark.excel" )
          .option( "useHeader", true )
          .option( "timestampFormat", "MM-dd-yyyy HH:mm:ss" )
          .load( "/Data1.xlsx", "/Data2.xlsx" );

It would be really nice to have above features.

**Comment by nightscape** [comment]
We're open to PRs 😉 
As a workaround, you can `map` over the paths and build a `union` of the `DataFrame`s.

**Comment by quanghgx** [comment]
Hi @pooja-murarka 
Please help check the spark-excel 0.14.0 (and up) for this feature. There is an [example in wiki](https://github.com/crealytics/spark-excel/wiki/Examples:-Load-Multiple-Files) as well.
Feel free to reopen this ticket in case of further issue.
