### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by qiulangmeng** [crealytics/spark-excel#748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to use org. Apache. Spark. SQL. DataFrameReader of load (paths: String *) method reads multiple excel files, but prompt Parameter "path" is missing in the options.

### Expected Behavior

I expect to be able to read multiple Excel files in parallel as normal, just like spark's native api reads files

### Steps To Reproduce

public static void main(String[] args) {
        SparkSession sparkContext = SparkSession.builder()
            //本地测试时开启
            .master("local[2]")
            .appName("测试")
            .getOrCreate();
        List<StructField> structFields = new ArrayList<>();
        structFields.add(DataTypes.createStructField("id", DataTypes.StringType, false));
        structFields.add(DataTypes.createStructField("name", DataTypes.StringType, false));
        structFields.add(DataTypes.createStructField("float", DataTypes.FloatType, true));
        structFields.add(DataTypes.createStructField("time", DataTypes.DateType, false));
        structFields.add(DataTypes.createStructField("timestamp", DataTypes.TimestampType, true));
        StructType structType = DataTypes.createStructType(structFields);
        sparkContext.read().format("com.crealytics.spark.excel")
            .option("sheetName", "Daily") // Required
            .option("useHeader", "true")
            .schema(structType)
            .load("C:\\Users\\86152\\Desktop\\fileTest\\testExcel.xlsx", "C:\\Users\\86152\\Desktop\\fileTest\\testExcel2.xlsx");
    }

### Environment

```markdown
- Spark version:2.3.4
- Spark-Excel version:0.9.9
- OS:windows10
- java version: 1.8
- Cluster environment
```

**Comment by nightscape** [comment]
Please try the newest version of spark-excel.

**Comment by qiulangmeng** [comment]
Which version of spark-excel is needed to solve the above problems?

**Comment by qiulangmeng** [comment]
Thank you very much for your advice, but can you specify which version of spark-excel can solve the above problems? Looking forward to your reply

**Comment by nightscape** [comment]
I'm not sure if any version of spark-excel solves the above problem, but for us maintainers it doesn't make sense to analyze/debug issues with outdated versions.
