### ISSUE TITLE
FileNotFoundException when trying to use com.crealytics.spark.excel 

### ISSUE THREAD

**Issue by kchatha** [crealytics/spark-excel#75]
My file is in s3 and I am trying to run this code from databricks. My s3 location is accessible by other libraries. Is it a bug?

 val df = sqlContext.read
    .format("com.crealytics.spark.excel")
    //.option("sheetName", "2018.06.30 GLSFT1 Data Tape") // Required
    .option("location","s3location")
    .option("useHeader", "true") // Required
    .option("treatEmptyValuesAsNulls", "false") // Optional, default: true
    .option("inferSchema", "true") // Optional, default: false
    .option("addColorColumns", "true") // Optional, default: false
    .option("startColumn", 0) // Optional, default: 0
    .option("endColumn", 99) // Optional, default: Int.MaxValue
    .option("timestampFormat", "MM-dd-yyyy HH:mm:ss") // Optional, default: yyyy-mm-dd hh:mm:ss[.fffffffff]
    .option("maxRowsInMemory", 20) // Optional, default None. If set, uses a streaming reader which can help with big files
    .option("excerptSize", 10) // Optional, default: 10. If set and if schema inferred, number of rows to infer schema from
    .option("skipFirstRows", 1) // Optional, default None. If set skips the first n rows and checks for headers in row n+1
    //.schema(myCustomSchema) // Optional, default: Either inferred schema, or all columns are Strings
    .load("GLS_Flow_201806.xlsx")

**Comment by nightscape** [comment]
You're mixing up things.
Delete the `.option("location",...)` part and specify the full URL in `load`

**Comment by kchatha** [comment]
Then I get this 

java.lang.IllegalArgumentException: Parameter "location" is missing in options.

**Comment by nightscape** [comment]
Seems you're using an outdated version.

**Comment by kchatha** [comment]
Thanks a lot for your quick response.
I am using spark-excel_2.11-0.9.17
My Spark version is spark 2.3.1
My Scala Version 2.11

**Comment by kchatha** [comment]
Thanks a lot. I cleaned up the classpath and now I am getting location exception but I am still getting other exception. This is the excel sheet I am getting from business so I can't even modify it manually. 
org.apache.spark.sql.AnalysisException: Attribute name "Contract Identification Number" contains invalid character(s) among " ,;{}()\n\t=".

**Comment by kchatha** [comment]
Thanks a lot. I cleaned up the classpath and now I am **not** getting location exception but I am still getting other exception. This is the excel sheet I am getting from business so I can't even modify it manually.
 org.apache.spark.sql.AnalysisException: Attribute name "Contract Identification Number" contains invalid character(s) among " ,;{}()\n\t=".

**Comment by nightscape** [comment]
Does this help? http://mail-archives.apache.org/mod_mbox/spark-user/201507.mbox/%3CCAAswR-6D7CGv1varyA0cYWnoH3nSr17gb+hypHORi3APGrhB7A@mail.gmail.com%3E

**Comment by kchatha** [comment]
Something is weird. I am creating a generic framework to extract any csv and excel. I am using spark-csv library , I extract the schema and save it and if schema is already there I will apply that schema in future.

However in case of Spark-excel library , when I extract schema I get all the column names, datatypes and nullable but I also get column names like this 
"StructField(ReportingPeriodEndingDate,StringType,true)_color".

**Comment by kchatha** [comment]
One more question: What should be the format of custom schema?

**Comment by kchatha** [comment]
When I convert excel to CSV, it generates a lot of empty columns.

**Comment by nightscape** [comment]
That strange-looking column should actually be called `"ReportingPeriodEndingDate_color"` and is a generated column that contains the cell color of the `"ReportingPeriodEndingDate"` column.
You can turn that of by leaving out the `.option("addColorColumns", "true")`.

**Comment by kchatha** [comment]
If I turn it off then it doesn't generate schema. I need to capture the schema.

**Comment by nightscape** [comment]
Wdym, "it doesn't generate schema"?
After reading from an Excel file to a `df: DataFrame`, you always have an associated schema with `df.schema`.

**Comment by kchatha** [comment]
Thanks a lot for your quick response and your help. I am able to solve the problem.
