### ISSUE TITLE
[BUG] Old excel files are not supported.

### ISSUE THREAD

**Issue by akshayjain3450** [crealytics/spark-excel#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error:

Exception in thread "main" org.apache.poi.hssf.OldExcelFormatException: The supplied spreadsheet seems to be Excel 5.0/7.0 (BIFF5) format. POI only supports BIFF8 format (from Excel versions 97/2000/XP/2003)
  

### Steps To Reproduce

Sample Spark Program: 
  ```
def read(): Unit = {
    val df = spark.read.format("excel").load("examples/elsec09t.xls")
    df.show(10)
  }
```
[elsec09t.xls](https://github.com/crealytics/spark-excel/files/11913880/elsec09t.xls)

### Environment

```markdown
- Spark version: 3.3.1
- Spark-Excel version: 3.3.1_0.18.5
- OS: MacOS
```

**Comment by nightscape** [comment]
Nothing we can do here...
Please convert your Excel files a non-ancient version 😉
