### ISSUE TITLE
Would need multiple sheets to generate for multiple dataset.

### ISSUE THREAD

**Issue by DeepaSaroja2017** [crealytics/spark-excel#77]

**Comment by nightscape** [comment]
Can you provide a little more explanation?
Do you want to write or read multiple sheets?

**Comment by nightscape** [comment]
Hi @DeepaSaroja2017,

I'm just publishing `0.11.0-beta1`. Once it has landed on Maven Central you can give it a try using the new [`.mode("append")`](https://github.com/crealytics/spark-excel/tree/append_to_existing_file#write-a-dataframe-to-an-excel-file) option.
This allows you to write Datasets into existing files, so you should be able to write different Datasets into different sheets by calling `.write` multiple times with different `dataAddress`es (see the [corresponding section in the README](https://github.com/crealytics/spark-excel/blob/append_to_existing_file/README.md#data-addresses)).

**Comment by nightscape** [comment]
Btw, just noticed this is a duplicate of #43. Closing this one.
