### ISSUE TITLE
 java.lang.RuntimeException: Unknown cell type 2

### ISSUE THREAD

**Issue by babu2015** [crealytics/spark-excel#78]
Hi we have one excel file where it has Hyperlink cells (type2 cells) it is giving us error.can you please help me to walk through this.

**Comment by quanghgx** [comment]
Hi @babu2015 

With a simple excel file with hyperlink cells and a notebook to test again spark-excel 0.14.0. Both are attached to this comment.

![Screenshot from 2021-10-03 10-22-01](https://user-images.githubusercontent.com/22023385/135738218-97ed6c47-fd0c-4518-bd84-1678ee861a7b.png)

It works, so I would like to resolve this issue. Feel free to reopen this ticket.
Sincerely,

[babu2015_78.xlsx](https://github.com/crealytics/spark-excel/files/7272629/babu2015_78.xlsx)
[babu2015_78.pdf](https://github.com/crealytics/spark-excel/files/7272630/babu2015_78.pdf)
