### ISSUE TITLE
Mentioned jar for scala 2.12 does not exist

### ISSUE THREAD

**Issue by Yuktaa1112** [crealytics/spark-excel#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

job failing with error when using a .xlsx file on 0.19.0 jar of spark excel-2.12-3.4.1

### Environment

```markdown
- Spark version: 3.4.1
- Spark-Excel version: 0.19.0
- OS:
- Cluster environment
-scala: 2.12.18
```

**Comment by christianknoepfle** [comment]
can you pls provide some more details?

**Comment by nightscape** [comment]
Please try `0.20.2`.
