### ISSUE TITLE
Reject bad data rows

### ISSUE THREAD

**Issue by pctodd** [crealytics/spark-excel#82]
I have a Scala app utilizing spark-excel 0.9.17 and am interested in rejecting rows that contain bad data as defined by the schema.  E.g. if a row has a column with a string in an Integer column, reject the row.  It seems, at least in the case of Integer types, non-numeric values are converted to zero, and the row is loaded into the data frame.  Is there anything similar to mode=DROPMALFORMED used for importing csv files that can be used in this case?  Such that in the example below, the second row would be rejected instead of converting the "x" to zero?  Thanks.

INPUT:
```
Name | Age | Comment
Joe | 25 | A
John | x | B
Bill | 35 | C
```
OUTPUT:
```
dfValid.printSchema()
root
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- Comment: string (nullable = true)

dfValid.show()
+----+---+-------+
|Name|Age|Comment|
+----+---+-------+
| Joe| 25|      A|
|John|  0|      B|
|Bill| 35|      C|
+----+---+-------+```

**Comment by nightscape** [comment]
Hi @pctodd, 
sorry for the late feedback...
This would definitely be possible, but I don't have time to do it.
If you're willing to create a PR, I'd happily review it.
The best place to start would be to make `DataColumn` a `PartialFunction[Seq[Cell], Either[Throwable, Any]]`, then `ExcelRelation` could decide if it wants to throw away a row for which any data conversion returned a `Left` value.

**Comment by anilkumarhv** [comment]
Input:
Name | Age | 
Joe | 25 | A
John | x | B
Bill | 35 | C

OutPut:

dfValid.printSchema()
root
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- _c2: string (nullable = true)

dfValid.show()
Exception in thread "main" java.util.NoSuchElementException: key not found: _c2

**Comment by quanghgx** [comment]
Hi @anilkumarhv 
 
Please try again with spark-excel 0.14.0. From our testing, it seems spark-excel works for this case. Detail in https://github.com/crealytics/spark-excel/issues/109#issuecomment-932857759
 
Thank you so much for such a detailed description. 
Would like to resolve this ticket, feel free to reopen it.
