### ISSUE TITLE
Match Error -spark-excel 2.11-11.0-beta2

### ISSUE THREAD

**Issue by kchatha** [crealytics/spark-excel#94]
scala.MatchError: Map(path -> s3a://cppib-edl-dev-landing/etl/test_excel.xlsx, maxrowsinmemory -> 20, excerptsize -> 10, useheader -> true, timestampformat -> MM-dd-yyyy HH:mm:ss, inferschema -> true, addcolorcolumns -> true, sheetname -> Sheet1) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)

**Comment by nightscape** [comment]
I just released `0.11.0`. Please have a look at the corresponding `CHANGELOG` and the `README` about the new `dataAddress` option which supersedes `sheetName`, `startColumn`, `endColumn` and `skipFirstRows`.

**Comment by TomLous** [comment]
I don't think the default setting of dataAddress is working?
It now only works if I add  `.option("dataAddress", "A1")` in my code.

No big deal, but FYI.
Thank you for the library
