### ISSUE TITLE
Combine efforts with HadoopOffice?

### ISSUE THREAD

**Issue by nightscape** [crealytics/spark-excel#95]
I only recently stumbled upon [HadoopOffice](https://github.com/ZuInnoTe/hadoopoffice/wiki) which takes a more generic approach and exposes Excel files as Hadoop File Format so that it can be used in Spark, Hive, Flink, ...
HadoopOffice also looks quite feature-rich and I'm wondering if it's worth the effort maintaining two very similar projects or if we should join efforts.
@jornfranke afais you're the main maintainer of HadoopOffice and I saw you commenting on another issue here.
Have you thought about this? Did you see any features that spark-excel has and HadoopOffice doesn't?

**Comment by jornfranke** [comment]
I think both have their use case. Spark excel is easier to use because it has a focused set of features and people who just need to read an Excel file without going to a complex set of features probably get faster results.  

HadoopOffice might be too complex for occasional usage.

**Comment by quanghgx** [comment]
Hi @nightscape and @jornfranke ,
Would like to close this ticket, it is great if we can open it again in the future.
Sincerely,
