### ISSUE TITLE
Cannot read simple xlsx

### ISSUE THREAD

**Issue by surtamikalai** [crealytics/spark-excel#96]
Here is a code I use:
val df = spark.read.format("com.crealytics.spark.excel")
      .option("sheetName", "test")
      .option("useHeader", "true")
      .load("c:/Users/Surta/git/datalake/cleansing/src/test/resources/test/excel/test.xlsx")

Version:
Spark 2.3.1
<dependency>
            <groupId>com.crealytics</groupId>
            <artifactId>spark-excel_2.11</artifactId>
            
            <version>0.11.0-beta3</version>
        </dependency>

Here is an error message:
Map(useheader -> true, sheetname -> test, path -> c:/Users/Surta/git/datalake/cleansing/src/test/resources/test/excel/test.xlsx) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)
scala.MatchError: Map(useheader -> true, sheetname -> test, path -> c:/Users/Surta/git/datalake/cleansing/src/test/resources/test/excel/test.xlsx) (of class org.apache.spark.sql.catalyst.util.CaseInsensitiveMap)
	at com.crealytics.spark.excel.DataLocator$.apply(DataLocator.scala:52)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:29)

File content:
![image](https://user-images.githubusercontent.com/18121766/49175665-2a795100-f35a-11e8-8253-145f892638b1.png)

**Comment by nightscape** [comment]
I just released `0.11.0`. Please have a look at the corresponding `CHANGELOG` and the `README` about the new `dataAddress` option which supersedes `sheetName`, `startColumn`, `endColumn` and `skipFirstRows`.
