### ISSUE TITLE
scala.MatchError for the version 0.11.0

### ISSUE THREAD

**Issue by lnuminer** [crealytics/spark-excel#99]
hi, thanks for your code. when the spark.read().load() (the spark version 2.3.1, spark-excel 0.11.0 ) is called, a exception of ' scala. MatchError: map(....) of (class CaseInsenstiveMap)' is throwed from 'loadV1Source' in DataFrameReader. but it is ok for the version 0.9.18.  moreover, is the format of xlsx supported only?

**Comment by nightscape** [comment]
You skipped the most interesting part in your error description, but I guess you're using the pre-`0.11.0` parameters.
Please read the README and CHANGELOG regarding `dataAddress`.
